### ISSUE TITLE
3.0 lacks markdown.version

### ISSUE THREAD

**Issue by keenerd** [Python-Markdown/markdown#710] opened 2018-09-23 12:44 UTC
In 2.6.11 (and older versions) one could `import markdown; markdown.version` and this is no longer present in 3.0: `AttributeError: 'module' object has no attribute 'version'`

Please add this to the [release notes](https://python-markdown.github.io/change_log/release-3.0/) if it was intentional.

**Comment by waylan** [comment] 2018-09-23 13:03
This is a duplicate of #709.

**Closed as completed** 2018-09-23 13:03 UTC

**Comment by keenerd** [comment] 2018-09-23 13:08
Apologies.  Didn't think to dig through the recent PRs.
