### ISSUE TITLE
Support CodeHilite lineseparator option

### ISSUE THREAD

**Issue by denizdogan** [Python-Markdown/markdown#817] opened 2019-04-13 11:03 UTC
Would make my day if we could configure `lineseparator` for CodeHilite.

The use case is a library that I've developed which, among other things, removes trailing whitespaces from its input: https://github.com/denizdogan/django-whiteless/

I use MkDocs to generate the documentation with example input and example output. Since I cannot change the `lineseparator` option for CodeHilite some examples look silly, because the extra newlines at the end of each input aren't included in the HTML output. For this reason, I'd like to be able to configure `lineseparator` to be `<br>`.

I've managed to configure this in my local version of Python-Markdown and was about to make a PR but couldn't quite figure out the unit test for when Pygments wasn't installed.

EDIT: Typo

**Comment by waylan** [comment] 2019-04-14 23:35
> I've managed to configure this in my local version of Python-Markdown 

How have you done this? I'm not aware of any `lineseparator` setting for [CodeHilite][1].

Or, in other words, I don't understand what you are having trouble with.

[1]: https://python-markdown.github.io/extensions/code_hilite/#usage

**Comment by denizdogan** [comment] 2019-04-15 08:14
@waylan My apologies, I actually meant the Pygments lineseparator option. What I've done in my local Python-Markdown is simply add a `lineseparator` argument to the `CodeHilite` constructor and then use that throughout the code in the same way as `linenums`.

**Comment by waylan** [comment] 2019-04-15 14:38
Ah, so you have forked the extension. Then you need to install it as a separate extension (under a new name) and list that new extension in your `mkdocs.yml` config file. The specifics of how to do this are out-of-scope for MkDocs. For help with forking/installing a Python-Markdown extension, please take that upstream to the Python-Markdown project.

Or you can address the issue upstream with the Python-Markdown project and if, your change is added, have assess to the feature in the next release of Python-Markdown.

**Comment by waylan** [comment] 2019-06-13 16:00
Hmm, Apparently in my previous response I missed that this was reported to Python-Markdown not MkDocs. Sorry about that.

In any event, there are currently a couple open issues regarding CodeHilite which contemplate expanding support to allow any and all Pygments options to be defined. I'm closing this as a duplicate of #334. See also #816 and #822.

**Closed as completed by waylan** 2019-06-13 16:00 UTC
Labels: duplicate
