### ISSUE TITLE
Allow `markdown` and possibly `commonmark` as output formats

### ISSUE THREAD

**Issue by twardoch** [Python-Markdown/markdown#545] opened 2017-02-14 22:29 UTC
Markdown is a very curious language. First, there is a large number of interpreters written in different languages, second, especially in PyMarkdown, there’s a large number of extensions. Just like “English” can be seen as a superset of all regional, professional and subcultural dialects of English (British, American, Legalese, Cockney, Twittertalk), I see Markdown as a superset of all dialects (like MultiMarkdown etc.), including all the constructs provided by various extensions. If one uses a lot of custom extensions, the MD flavor he or she uses could be called an “idiolect”. 

Then, we have Commonmark as the minimal set of constructs that should be supported by all implementations, and we have all the various stages in between (e.g. the subset of a certain idiolect that is supported by a particular processor). We have different processors such as Python-Markdown (Python), Pandoc (Haskell), Kramdown (Ruby, used by Jekyll), Redcarpet (Ruby, used by Github), Remarkable and Showdown (both JS).  

Markdown often changes hands. Today, I may have my own MD idiolect with all kinds of fancy extensions and constructs, but then I may be expected to hand over a more specific flavor or dialect of Markdown — when submitting a publication, using it in a Github wiki or entering it into some CMS. 

PyMarkdown today only outputs HTML, which I think is a limitation. I wonder how difficult it might be to add support for outputting various Markdown dialects from PyMarkdown. Since some extensions are preprocessors, I might want to only utilize PyMarkdown to run the preprocessors. I would feed in a Markdown idiolect and would get back a more standardized MD dialect. 

Another scenario would be that I might have some Markdown idiolect which uses lots of other types of extensions (e.g. block processors), and I’d like to get back a more broadly supported dialect of Markdown, that, for example, only uses the CommonMark (or "extension-less PyMarkdown") constructs while all the constructs supported by extensions have been converted to HTML. 

Is this something that PyMarkdown developers might be willing to consider?

**Comment by waylan** [comment] 2017-02-14 23:49
This is a duplicate of #338. Specifically, please see [my comment][1]. One thing I didn't mention there is that I do not consider CommonMark to be Markdown at all (perhaps a much younger sister) and I have no interest in it.

This issue is closed and locked as I have no interest in discussing it further. Any attempts to change my mind would be a waist of both our time. So as a courtesy, I'm not allowing any discussion on the matter.

[1]: https://github.com/waylan/Python-Markdown/issues/338#issuecomment-54697337

**Closed as completed by waylan** 2017-02-14 23:49 UTC
