### ISSUE TITLE
Parsing html tags slows down dramatically if the same document has a large table.

### ISSUE THREAD

**Issue by nophead** [Python-Markdown/markdown#1100] opened 2021-01-29 16:16 UTC
I have some Python code that automatically generates an assembly manual for a project in markdown format with a few html tags and then converts it to html with `python -m markdown -x tables -x sane_lists`. For a small project this is fast (0.3s) but as a project grows it slows down massively. For my latest project it takes 80s to process about 350KB.

I make two versions of the document, one for viewing in a web browser and another for printing that has page breaks in it generated by div tags. Without 35 of these div tags the same file takes 12s to process, i.e. adding page breaks slows it down by a factor of more than 6! 

The div tags are `<div style="page-break-after: always;"></div>` but it doesn't seem any faster if the are just `<div></div>` . Using p tags instead of div seems to make no difference to the speed.

There is also a bill of materials which is a markdown table with some HTML span tags in it. Without that table but with the page breaks only takes 0.7s. Removing the span tags from the table column headers doesn't speed it up at all, if anything slightly slower. The table is about 300KB of the 350KB though.

So it appears that a table with lots of rows and columns slows down the processing by a factor of 17 without page breaks but adding page breaks as well as the table makes it 114 times slower than without either. I don't see any connection between the page breaks and the table. I think it is probably just because the file is 7 times bigger with it.

Why do div or p tags slow long files even more? I would expect empty tags to take next to no time to parse and pass through and I wouldn't expect it to depend on the file size or size of a table.

I am using markdown 3.3.3 with Python 3.8.0 on Win7 64bit.

**Comment by waylan** [comment] 2021-01-29 16:55
Actually, parsing HTML is a very complex problem. In fact, it is the most complicated part of the Markdown parser.

As of version 3.3, all raw HTML is parsed by a custom instance of Python's standard library [html.parser.HtmlParser][1] (as defined [here][2]). Early tests showed that it was faster than our own custom built parser (in versions < 3.3). However, by the time we released a feature complete version 3.0, things had slowed down. The problem is that I don't use much (if any) raw HTML in my own personal documents, so it's hard for me to test real-world use cases. I would be interested to see how version < 3.3 compares with your same documents.

Regardless, performance has never been a high priority for this project. We are more concerned with parsing accuracy and ease of maintenance.

[1]: https://docs.python.org/3/library/html.parser.html
[2]: https://github.com/Python-Markdown/markdown/blob/master/markdown/htmlparser.py

**Comment by nophead** [comment] 2021-01-29 18:11
Version 3.0 is a little faster in both cases but there is still a big slowdown when page breaks are added. Why does the time taken to parse a fixed number of div tags depend on the size of rest of the file in a very non-linear way?

**Comment by nophead** [comment] 2021-01-29 18:19
Is `rawdata` the whole file? I can imagine it might get slow when the file is big because it is continually passing `rawdata` around and slicing it.

**Comment by waylan** [comment] 2021-01-29 18:25
> Is `rawdata` the whole file? I can imagine it might get slow when the file is big because it is continually passing `rawdata` around and slicing it.

If you are talking about `rawdata` in `HtmlParser`, yes, in most cases it is the entire document. As I stated previously, we are more concerned with parsing accuracy and ease of maintenance than performance. Using `HTML` parser gives us that.

**Comment by nophead** [comment] 2021-01-29 18:36
I can understand raw performance might not be a priority, but when it gets to be quadratic, or in this case worse, it sets a limit on how big  file can be if it has HTML tags.

In this case making the file 7 times longer takes it 114 times slower, which happens to be 7^3/3, so perhaps cubic. Since the table is assembly names on one axis and unique parts on the other the file length is sort of proportional to the square of the project complexity, which is why it has suddenly become an issue on my largest project.

**Comment by waylan** [comment] 2021-01-29 18:45
I see two options:

1. Reactor the old parser and address all of the many issues that it had.
2. Provide a new HTML parser which does not require any third-party dependencies.

In either case I do not have the time to do the work. So, if you would like this matter addressed, then feel free to do the work and provide a PR.

**Comment by nophead** [comment] 2021-01-29 21:01
An odd thing I have noticed is I have a similar number of `a` tags and `span` tags and they don't cause a massive slowdown like `div` and `p`. If I put exactly the same data in a span, i.e. `<span style="page-break-after: always;"></span>` it is 50 seconds faster but it then doesn't work as a page break. I can't think of any reason why `div` should harder to parse than `span`.

**Comment by nophead** [comment] 2021-01-29 21:20
Which version has your old parser? 3.0 seems to behave too similar to 3.3.3 in this strange way to believe it is a completely different  parser. If it is then it might be something outside the parser to blame. Does markdown do anything special with `div` and `p` tags that it doesn't do with `a` and `span`?

**Comment by waylan** [comment] 2021-01-29 21:20
> An odd thing I have noticed is I have a similar number of `a` tags and `span` tags and they don't cause a massive slowdown like `div` and `p`.

That is interesting. As a reminder, Markdown handled inline tags differently than block-level tags (Markdown is parsed within inline tags, but not block-level tags). Therefore, those tags are handled differently by different code at a different location within the parsing process. When parsing inline tags, we just ignore anything between `<` and `>` and that's it. Whereas, for block level HTML, we need to identify the opening tag and the matching closing tag, accounting for nested tags (consider the complexity of parsing four `div` tags all nested one within the other and how that differs from `div` tags which are siblings of each other). Even if you don't use complex HTML, we still need to check to confirm it's not complex. So, yeah, of course, block-level tags are slower to parse. We are actually parsing them as HTML.

**Comment by nophead** [comment] 2021-01-29 22:18
But `span` can be nested just like `div` in my understanding of HTML?

I tried `<div style="page-break-after: always;"/>` to try to avoid the need to search for the closing tag but it included all the rest of the document. I think it also doesn't like `a` anchors done like that but I think they are valid HTML, not sure about `div`.

**Comment by waylan** [comment] 2021-01-29 23:37
> But `span` can be nested just like `div` in my understanding of HTML?

True, but we don't care about when one `span` ends and another begins because we will parse the content the same either way. If you have the document:

```
Foo <span> bar </span> baz.
```

We simply substitute the tags like this:

```
Foo placeholder1 bar placeholder2 baz.
```

And then parse the entire paragraph for inline Markdown. After we're done, we then swap the tags back in for the placeholders. We don't care about whether a tag has been closed or another tag has been opened. And the string substitutions are very quick.

However, for raw blocks, we need to match the opening and closing tags, and that takes a lot more processing time. If you disagree, then by all means, implement a parser yourself and show me that it works. Otherwise, I'm not going to continue wasting my time arguing over the current implementation.

**Comment by nophead** [comment] 2021-01-31 00:14
An odd thing is it doesn't seem to matter how many `div` tags I have, even one will slow it down by about a minute and further ones don't make much difference. So it seems to be a one off hit to have block-level tags in a large document. I think something odd is happening rather than HTML parsing being slow, especially as it seems to behave roughly the same with version 3.0, if that has a completely different HTML parser.

**Comment by waylan** [comment] 2021-02-01 16:13
I decided I should actually test the claims made here. I created the following:

### plain.md

```markdown
Foo

Bar

Baz
```

### raw.md

```markdown
<div>
Foo
</div>

<div>
Bar
</div>

<div>
Baz
</div>
```

### time_it.py

```python
import markdown
import timeit

with open('plain.md') as f:
    plain = f.read()

with open('raw.md') as f:
    raw = f.read()


num, dur = timeit.Timer(lambda: markdown.markdown(plain)).autorange()
print('Plain:', dur / num)
num, dur = timeit.Timer(lambda: markdown.markdown(raw)).autorange()
print('Raw:  ', dur / num)
```

### Result

```bash
$ python time_it.py
Plain: 0.0005772590359999996
Raw:   0.0008446562780000005
```

Then I modified `raw.md` by removing one raw block:

```markdown
<div>
Foo
</div>

<div>
Bar
</div>
```

and got:

```bash
$ python time_it.py
Plain: 0.0005886643080000001
Raw:   0.0006553971999999999
```

And then again:

```markdown
<div>
Foo
</div>
```

and got:

```bash
$ python time_it.py
Plain: 0.0005676058920000001
Raw:   0.00049182407
```

which is faster that the plain Markdown document. I'm not seeing anything to be concerned about here.

**Comment by nophead** [comment] 2021-02-01 19:41
It doesn't slow down unless the document is large. I started with a 100 page document that is 350KB long in markdown format.

The time to process just one block level tag can add one minute then but adding more tags doesn't add much more time at all. So the time to parse HTML is not the problem. It seems to be a one hit overhead as soon as you have a block level tag in a large file.

My workaround is to use empty span tags to create an invisible marker for page breaks. I then post process the HTML and replace the empty spans with the div page break. That reduced my built time from 80s to about 18s. I then reduced my table to about half its size by removing small sub assemblies and only listing the larger ones. That halved the file size to 168K and now only takes 3.3s!

So the problem is build time is proportional to a high power of file size and there is also a one off hit with block level tags that is also proportional to a high power of file size. On small files it is lightning fast, less than a second for 100 pages, but due to the time not being linear it can suddenly become unreasonable slow.

**Comment by waylan** [comment] 2021-02-01 19:58
Could you please provide an example file which demonstrates the alleged behavior? I understand if you don't want to provide real content, but something from a lorem ipsum generator would suffice. And as I generally try to avoid downloading random files without the ability to inspect them, I would suggest posting it as a [gist](https://gist.github.com) (or something similar).

**Comment by nophead** [comment] 2021-02-01 20:52
Here is an example with my shortened table and one empty div: https://gist.github.com/nophead/b4d044d1ad2edeeebab65e80a11891c2

It takes around 10s seconds but if you change the empty div on line 7 to a span it will be only about 2 seconds. Then you can change all the the empty spans to divs and it will only be around 10 seconds again. It is a lot faster than with a longer table but it demonstrates one div makes a big difference but more don't add much.

There is a big table near the beginning. Doubling its size makes it take 80s seconds with div and 18 seconds with span. I can post that version as well if you need it. It is just further along the exponential curve by doubling the file size a single div adds about 10 times the time.

**Comment by waylan** [comment] 2021-02-01 21:27
I'm still not seeing an issue. In fact, it was actually faster with the `div` tag than with the `span` tag, although the difference is negligible. I also included a version where all `span` tags were replaced by `div` tags. That made no discernible difference. For kicks, I ran it multiple times and am getting the same sorts of results. On the second two runs, the all divs file was actually the fastest.

```
span: 1.360332026
div:  1.2865597180000004
divs: 1.2949757949999996

span: 1.342757781
div:  1.3219384980000002
divs: 1.3209831040000002

span: 1.3259271030000002
div:  1.284127558
divs: 1.2953357619999997
```

Note: as the document contains Markdown tables, I enabled the `tables` extension, but no others. 

```python
import markdown
import timeit

with open('span.md') as f:
    span = f.read()

with open('div.md') as f:
    div = f.read()

with open('divs.md') as f:
    divs = f.read()


num, dur = timeit.Timer(lambda: markdown.markdown(span, extensions=['tables'])).autorange()
print('span:', dur / num)
num, dur = timeit.Timer(lambda: markdown.markdown(div, extensions=['tables'])).autorange()
print('div: ', dur / num)
num, dur = timeit.Timer(lambda: markdown.markdown(divs, extensions=['tables'])).autorange()
print('divs:', dur / num)
```

I should also note that I have run these tests on a 2011 Mac (11 years old) with many other apps running and very limited resources.

**Comment by waylan** [comment] 2021-02-01 21:29
Ahh, I see the problem now. I was running the latest in `master`. I just checkout out version 3.3.3 and now I see the issue:

```
$ git checkout 3.3.3
$ python time_it.py
span: 2.882688641
div:  9.971139373
divs: 9.960951536000001
$ git checkout master
$ python time_it.py
span: 1.353035702
div:  1.2638967030000001
divs: 1.2991750149999999
```

So this was resolved in one of the bug fixes which will be available in the next release.

**Closed as completed by waylan** 2021-02-01 21:29 UTC
