### ISSUE TITLE
codehilite produces invalid html when used within a list

### ISSUE THREAD

**Issue by fladd** [Python-Markdown/markdown#588] opened 2017-10-11 09:42 UTC
When using codeblocks within a list, the list item (if it contains other text as well before the codeblock) is wrapped in a `<p></p>` element. Within that, when the codeblock comes, codehilite puts a `<div class="codehilite"><pre><code># Code goes here ...
</code></pre></div>` in there.

This is invalid html: https://stackoverflow.com/questions/10763780/putting-div-inside-p-is-adding-an-extra-p

Why not just add the class to the `<pre>` element: `<pre class="codehilite"><code># Code goes here ...
</code></pre>`? This would solve the issue I think.

**Comment by fladd** [comment] 2017-10-11 13:28
...or replace the `<div>` with a `<span>`.

**Comment by facelessuser** [comment] 2017-10-11 13:28
But the code block shouldn't be wrapped in the paragraph tag previously.  It's not part of the paragraph.  It should be it's own block as denoted by the empty line between the code block and paragraph.

Even in non-list examples per the Markdown spec, they are not included in the prior paragraph: https://daringfireball.net/projects/markdown/syntax#precode.

Markdown separates blocks by empty lines.  That is why you get two paragraphs in this case:

```
One paragraph

Two paragraph
```

And two blocks with this

```
One paragraph

     A separate block
```

So I would expect the first block in a list to be a paragraph, and the second to be the code block in this example:

```
- I am a paragraph

        I am a code block
```

**Comment by facelessuser** [comment] 2017-10-11 13:30
Also, it will be much clearer when you explain an issue to also post a Markdown source example that causes the bug as it will ensure there is no ambiguity.

**Comment by facelessuser** [comment] 2017-10-11 13:32
For clarity, I don't think Markdown puts the code block in the paragraph to begin with, I believe the code should be, and is, written outside of the paragraph in the HTML source before it ever gets to the browser.

**Comment by waylan** [comment] 2017-10-11 13:35
The codehilite extension passes the code block to Pygments to do the highlighting. Pygments returns a `div` which is then simply inserted into the document to replace the code block. We don't have any control over what Pygments returns (except as they provide through their limited options), so we get a `div`. I've never been a fan of how they wrap their code blocks, but not enough to be motivated to write a custom Pygments Formatter. That being the case, the discussion over a `div` verses some other wrapping tag is not up for discussion here. You should take that upstream and address that with the Pygments developers.

Now on to the bug being reported. Please provide all three of the following: (1) a simple example of the Markdown input, (2) the actual output and (3) what output you expected.

**Comment by fladd** [comment] 2017-10-11 14:48
Running the following through Python Markdown

    1. Make sure [Python 2][] is installed 
 
    2. Install the Python packages [Markdown][], [PyMdownExtensions][] and [Pygments][] (optional, for code highlighting): 
       ``` 
       pip install markdown pymdown-extensions pygments 
       ``` 

    [Python 2]: http://www.python.org 
    [Markdown]: https://pythonhosted.org/Markdown/ 
    [PyMdownExtensions]: http://facelessuser.github.io/pymdown-extensions 
    [Pygments]: http://pygments.org 

will produce the following invalid HTML

```
<ol>
<li>
<p>Make sure <a href="http://www.python.org">Python 2</a> is installed </p>
</li>
<li>
<p>Install the Python packages <a href="https://pythonhosted.org/Markdown/">Markdown</a>, <a href="http://facelessuser.github.io/pymdown-extensions">PyMdownExtensions</a> and <a href="http://pygments.org">Pygments</a> (optional, for code highlighting): 
   <div class="codehilite"><pre>pip install markdown pymdown-extensions pygments 
</pre></div>
</p>
</li>
</ol>
```

**Comment by facelessuser** [comment] 2017-10-11 15:29
Okay:

1. Fenced blocks are not supported in lists unless you are using something like `pymdownx.superfences`.  So if you are using `markdown.extensions.fenced_code`, you should not be using them in a list.  See warning in `fenced_code` docs: https://pythonhosted.org/Markdown/extensions/fenced_code_blocks.html.

2. If you are using [SuperFences](http://facelessuser.github.io/pymdown-extensions/extensions/superfences/). While I don't explicitly mention this, fences are meant to be separate blocks and it is intended that you separate them with an empty line before them.  I assume the same is true for the `fenced_code` extension, but due to the way they are implemented, this can currently occur.

So ignoring the fact that Python Markdown's `fenced_code` extension does not support fences in lists, the code block should not be included in the preceding paragraph, so that is a bug.  The browser corrects it as it should by separating out.

I imagine the best course of action is to either not capture and convert a fence that is not preceded by an empty line (except when at the start of a file).  Or, when inserting the converted form back into the file, a new line is injected before it (when one is not already present), to prevent it from being included in the preceding paragraph.  Only @waylan, can weigh in on what he'd like for `fenced_code`.

Now as the maintainer of SuperFences which does support nesting fences in lists, I would only attempt one of the fixes above.  Code blocks being encapsulated in a div should have no bearing on this issue as I feel the issue is it is getting included in the paragraph in the first place. So my approach would be as I suggested above.

So if you are using SuperFences, create an issue there, but in the short term, put an empty line before your fence.

If you are using `fenced_code`, don't put the fenced block in a list, and put an empty line before your fence and @waylan will decided what, if anything, should be done in `fenced_code` to prevent this.

**Comment by facelessuser** [comment] 2017-10-11 15:38
Just to illustrate the point, inspect this post in your browser to see what GitHub does:

1. Make sure [Python 2][] is installed 

2. Install the Python packages [Markdown][], [PyMdownExtensions][] and [Pygments][] (optional, for code highlighting): 
   ``` 
   pip install markdown pymdown-extensions pygments 
   ``` 

[Python 2]: http://www.python.org 
[Markdown]: https://pythonhosted.org/Markdown/ 
[PyMdownExtensions]: http://facelessuser.github.io/pymdown-extensions 
[Pygments]: http://pygments.org 

<img width="238" alt="inspect" src="https://user-images.githubusercontent.com/1055125/31450866-cfbaa4f4-ae67-11e7-9114-290a44b09e5d.png">

Not included in the paragraph.

**Comment by fladd** [comment] 2017-10-11 16:23
I am actually using super fences. However, leaving a blank line in front of the codeblock (as you suggest) will break the list:

<img width="927" alt="image" src="https://user-images.githubusercontent.com/2971539/31453026-e1a427b4-aeb0-11e7-93e2-04f26dc62c8f.png">

**Comment by facelessuser** [comment] 2017-10-11 16:24
Because your example doesn't indent by 4.  Your example indents by 3.

**Comment by fladd** [comment] 2017-10-11 16:28
Oh right. Did not know that this was needed. In all other Markdown variants, I usually indent by three to align it with the list item itself...

Thanks!

**Comment by facelessuser** [comment] 2017-10-11 16:29
Yeah, Python Markdown sets a general indentation width of 4 by default.  So anytime you need to indent, it is by that value, unless you override that value to something else.

**Comment by waylan** [comment] 2017-10-11 16:55
So is there a bug here? Fenced code blocks must be surrounded by blank lines and can’t be nested. Yes, you get weird output if you don’t follow those rules, but the weird output is the clue that you need to edit your Markdown. I’m not seeing a bug and all the wrong assumptions are already addressed in our documentation. 

I’m also assuming the invalid HTML is generated by SuperFences as fenced_code would never see that as a code block. Which means this is an upstream (downstream?) problem which should be reported there. 

If my assumptions are correct then this should be closed.

**Comment by facelessuser** [comment] 2017-10-11 17:04
@waylan , the issue is not unique to SuperFences as the list has nothing to do with what is seen.  Below is the same issue reproduced in Fenced Code.

```py
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import markdown
>>> text = """A paragraph
... ```
... some code
... ```
... """
>>> markdown.Markdown(extensions=['markdown.extensions.extra']).convert(text)
'<p>A paragraph</p>\n<pre><code>some code\n</code></pre>'
```

The question is if you care to guard against it or just tell people to stop leaving out the empty line before the fence.

**Comment by facelessuser** [comment] 2017-10-11 17:08
Never mind, I take it back, the issue does not reproduce.  I didn't look close enough at my example.  I guess it can be closed as this is SuperFences specific.

**Closed as completed** 2017-10-11 17:10 UTC

**Comment by facelessuser** [comment] 2017-10-11 17:12
I've closed this issue as it is downstream.

**Comment by facelessuser** [comment] 2017-10-12 14:50
Just an FYI on this.  SuperFences is kind of a workaround to get nested fences despite Python Markdown's weakness in parsing these kinds of blocks, so there are concessions that are made to pull this off (the behavior above being one of them).  After reviewing the code, due to constraints that are currently unavoidable, SuperFences will *always* require empty lines around fences.

Personally I think this is just good practice despite other parsers allowing them without, but it is not going to possible (or possibly better stated, I have no plans to put in a more complicated system to accommodate this corner case as it is too much work for something I already have a bias against). 

In the future, my plan is to alter the the parsing logic so it will be aware of whether it is preceded by empty lines, and most likely, those without will not be counted as fences to avoid confusion in this type of corner case.  In the short term, I've updated the documentation to formally state this as a requirement.

Feel free to hop on over the the pymdown-extension issue to read more details on why this is difficult to handle: https://github.com/facelessuser/pymdown-extensions/issues/114.  Feel free to ask more questions over there if you want more details on why this is so difficult, but most likely my stance is going to remain as I am not expecting a huge overhaul on how Python Markdown handles blocks that are like fences.
