### ISSUE TITLE
```c <code block> ``` is not compiled as code block

### ISSUE THREAD

**Issue by Poornahandra** [Python-Markdown/markdown#1162] opened 2021-07-27 15:30 UTC
For example :
![image](https://user-images.githubusercontent.com/38465746/127182507-043e82ae-95a1-423a-acf9-754190f0bc52.png)

I am getting as
![image](https://user-images.githubusercontent.com/38465746/127182573-3dacb9fc-d6c5-4583-b370-7b643e74c195.png)

**Comment by facelessuser** [comment] 2021-07-27 16:07
1. Please, please post examples as plain text. Pictures are fine, but also posting copy/pastable examples helps developers in reproducing issues.

2. Are you enabling some sort of fenced code extension? `fenced_code` is the implementation that ships with Python Markdown and must be enabled for it to take effect, but it only works at the root level (no nesting under lists etc.). There is also the [SuperFences](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/) extension which allows for nesting fenced code under lists etc.

It is important to note that fenced code is not part of the Markdown spec and is usually implemented as an addition to the original Markdown spec.

**Comment by waylan** [comment] 2021-11-03 14:20
I'm closing this due to a lack of follow-up. If more information is provided we can reopen the issue.

**Closed as completed by waylan** 2021-11-03 14:20 UTC
Labels: more-info-needed
