### ISSUE TITLE
importib-metadata is too much constrainted for older environment than python 3.10

### ISSUE THREAD

**Issue by Krilivye** [Python-Markdown/markdown#1227] opened 2022-03-01 07:54 UTC
Hello team, thanks for the work!

Regarding this https://github.com/Python-Markdown/markdown/issues/1203 issue, I also ran into a dependency problem regarding the latest markdown 3.3.6 pushing for using importlib-metadata>=4.4 and latest flake8 constraining it to importlib-metadata<4.3 💥 : conflict.

I'm a bit confused as I see that markdown support python 3.6->3.10.
According to importlib-metadata Changelog, https://importlib-metadata.readthedocs.io/en/latest/history.html markdown should need only 3.0.0 to support python 3.6.

So I would suggest restricting importlib-metadata to >=3.0.0 to keep backward dependencies compatible code with the ecosystem (who is not up to date with python 3.10 which requires 4.4 ;) ).

I'm downgrading markdown in my projects to 3.3.4 due to that but it makes me sad.

Theorie reasoning behind.
I'm a user of both flake8 and markdown (requirements.txt only contains flake8 and markdown).
constraints are free (no pinned version)
on a python3.6->3.9 I won't be able to install the latest markdown -> conflict
on python3.10 flake8 will be the bad guy... but that is expected as flake8 does not support python3.10 yet (nor 3.9).

With a lighter constraint, I'll be able to have markdown installed in every python3.6 -> 3.10 ecosystem

Also according to importlib-metadata 1.4 is used in python (stlib) 3.8.

I also discovered that pip6 support python version constraint so it could be something like that (didn't test it):

```
importlib-metadata >=1.4, <4.4; python_version <= '3.10'
importlib-metadata >=4.4 ; python_version >= '3.10'
```

_Originally posted by @Krilivye in https://github.com/Python-Markdown/markdown/issues/1203#issuecomment-1054619758_

**Comment by waylan** [comment] 2022-03-01 13:54
> I'm a bit confused as I see that markdown support python 3.6->3.10.

There is nothing to be confused about. So long as you don't have any third party libs installed which don't conflict, then Python-Markdown works in all of those Python versions. The problem is that some more popular third party packages have been slow to adopt Python 3.10. It is those packages which are causing the problem.

We are not going to revert our support of Python 3.10. However...

> ```
> importlib-metadata >=1.4, <4.4; python_version <= '3.10'
> importlib-metadata >=4.4 ; python_version >= '3.10'
> ```

That might be a reasonable way to approach this. I hadn't thought of that. A PR is welcome.

**Comment by mitya57** [comment] 2022-03-01 21:16
We need at least 3.6.0 to support `group` argument.

Also why putting an upper bound? I would suggest something like this if we want to change it:

```
importlib-metadata >=3.6
importlib-metadata >=4.4; python_version >= '3.10'
```

**Comment by waylan** [comment] 2022-04-01 15:57
Upon further review, I am closing this as wontfix. As explained in #1228 (and elsewhere), Python 3.10's [Release Notes](https://docs.python.org/3/whatsnew/3.10.html#importlib-metadata) states that Python 3.10 has feature parity with import-metadata 4.6. Therefore, my assumption is that any earlier version of importlib-metadata will not behave exactly as expected in every edge case. And I'm not interested in testing every edge case. Therefore, we will not be supporting any earlier version.

**Closed as completed by waylan** 2022-04-01 15:57 UTC
Labels: core, wontfix
