### ISSUE TITLE
module 'markdown' has no attribute 'version'

### ISSUE THREAD

**Issue by mbrochh** [Python-Markdown/markdown#715] opened 2018-09-26 03:14 UTC
I'm on Python 3.6.6. `pip freeze` shows that I have `Markdown==3.0.0`

When I run `ipython`, I get this:

```
import markdown
markdown.version

AttributeError: module 'markdown' has no attribute 'version'

markdown.__version__
'3.0'
```

It seems this is already fixed, but everyone who has just `Markdown` in their requirements will get version 3.0.0 and it might crash other libraries (in my case django-rest-framework). Would it be possible to release 3.0.1 soon-ish?

**Comment by facelessuser** [comment] 2018-09-26 03:18
Duplicate of #710.  See also #711 and #714.

**Closed as completed** 2018-09-26 03:22 UTC
