### ISSUE TITLE
Space

### ISSUE THREAD

**Issue by demoh2019** [Python-Markdown/markdown#1213] opened 2022-01-21 12:25 UTC
```
**Порядка 1 тысячи жителей Сочи** [остались](https://t.me/tass_agency/95997) **без водоснабжения из\\-за повреждения водопровода в результате оползня**
```
The link is not indented and stuck to the text

**Comment by facelessuser** [comment] 2022-01-21 14:48
I'm not sure I understand what is being described here. Why do you think the link should be indented? From what I see, what you posted translates to:

```html
<p><strong>Порядка 1 тысячи жителей Сочи</strong> <a href="https://t.me/tass_agency/95997">остались</a> <strong>без водоснабжения из-за повреждения водопровода в результате оползня</strong></p>
```

This is exactly what I would expect. You've written the content as a single paragraph, and it converts to HTML as a single paragraph.

**Comment by demoh2019** [comment] 2022-01-22 12:51
This is how it appears in markdown:
<img width="868" alt="Снимок экрана 2022-01-22 в 14 52 08" src="https://user-images.githubusercontent.com/75473925/150639250-69755ca7-21d6-4480-967d-5c3bd83b91e4.png">

This is how the library is converted:
<img width="922" alt="Снимок экрана 2022-01-22 в 14 50 24" src="https://user-images.githubusercontent.com/75473925/150639200-eb91fc20-a742-40be-ab3f-173f1afcac55.png">

I expected indentation after ** to be preserved

The indents after and before ** should have gone inside the `<strong>` tag

**Comment by demoh2019** [comment] 2022-01-22 13:06
> I'm not sure I understand what is being described here. Why do you think the link should be indented? From what I see, what you posted translates to:
> 
> ```
> <p><strong>Порядка 1 тысячи жителей Сочи</strong> <a href="https://t.me/tass_agency/95997">остались</a> <strong>без водоснабжения из-за повреждения водопровода в результате оползня</strong></p>
> ```
> 
> This is exactly what I would expect. You've written the content as a single paragraph, and it converts to HTML as a single paragraph.


In html it is possible that indentation is added after `<strong> `when it should be added inside

**Comment by facelessuser** [comment] 2022-01-22 15:32
This script:

```py
import markdown

MD = """
**Порядка 1 тысячи жителей Сочи** [остались](https://t.me/tass_agency/95997) **без водоснабжения из\\-за повреждения водопровода в результате оползня**
"""

html = markdown.markdown(MD)

print(html)
```

Produces this:

```html
<p><strong>Порядка 1 тысячи жителей Сочи</strong> <a href="https://t.me/tass_agency/95997">остались</a> <strong>без водоснабжения из-за повреждения водопровода в результате оползня</strong></p>
```

When run in a browser we get:

<img width="845" alt="Screen Shot 2022-01-22 at 8 28 37 AM" src="https://user-images.githubusercontent.com/1055125/150645008-610dbe02-a17d-4718-b443-0206e365cfd1.png">

It seems to be working as expected. I cannot reproduce the lack of spaces. The HTML is rendered with expected spaces and HTML also renders it with expected spaces. Is there something I am missing?

**Comment by demoh2019** [comment] 2022-01-22 17:38
I used djnago with {% spaceless %} which removed the extra padding and didn't notice it. It seems to me that the indentation should be inside the `<strong>` tag. You can close the issue if I'm wrong)

**Comment by facelessuser** [comment] 2022-01-22 17:45
No, the space should not be in the `<strong>` tag. You'll notice even GitHub's Markdown parser doesn't do that:

```html
<p dir="auto"><strong>Порядка 1 тысячи жителей Сочи</strong> <a href="https://t.me/tass_agency/95997" rel="nofollow">остались</a> <strong>без водоснабжения из\-за повреждения водопровода в результате оползня</strong></p>
```

No doubt, Django is causing you the issues. If anything, I'd adjust how you are using the `spaceless` feature. I see no problems with our output, and it seems it renders fine in browsers. As we cannot control how Django does things or how people use Django features, I think this should be closed.

Marked `wontfix` for the reasons above.

**Closed as completed by facelessuser** 2022-01-22 17:45 UTC
Labels: more-info-needed, wontfix
