### ISSUE TITLE
`attr_list` extension doesn't work well with `tables` extension

### ISSUE THREAD

**Issue by pkubiak** [Python-Markdown/markdown#891] opened 2019-12-30 19:59 UTC
Hi, 
I have tried to add some styles to table created with `tables` extension using `attr_list` extension, but it works quite strange. For markdown:

```markdown
| column 1 | column 2 |
|----------|----------|
| value 1 {: .text-primary} | value 2 {: .text-danger }|
{: .text-success }
```
it creates new empty row with cell of given class (with `extensions=['markdown.extensions.extra']`):
```html
<table>
<thead>
<tr>
<th>column 1</th>
<th>column 2</th>
</tr>
</thead>
<tbody>
<tr>
<td class="text-primary">value 1 </td>
<td class="text-danger">value 2 </td>
</tr>
<tr>
<td class="text-success"></td>
<td></td>
</tr>
</tbody>
</table>
```
instead of setting class of whole table what I would expect:

```html
<table class="text-success">
<thead>
<tr>
<th>column 1</th>
<th>column 2</th>
</tr>
</thead>
<tbody>
<tr>
<td class="text-primary">value 1 </td>
<td class="text-danger">value 2 </td>
</tr>
</tbody>
</table>
```

Is it a correct behavior of `attr_list` extension? or is there same workaround to style whole table?

```python
>>> markdown.__version__
'3.1.1'
```

**Comment by waylan** [comment] 2019-12-30 22:08
This is a duplicate of #312.

**Closed as completed by waylan** 2019-12-30 22:08 UTC
