### ISSUE TITLE
CommonMark

### ISSUE THREAD

**Issue by noraj** [Python-Markdown/markdown#851] opened 2019-07-25 12:32 UTC
Respect CommonMark (https://commonmark.org/) A strongly defined, highly compatible specification of Markdown

> Why is CommonMark needed?
>
> John Gruber’s canonical description of Markdown’s syntax does not specify the syntax unambiguously. 
>
> Because there is no unambiguous spec, implementations have diverged considerably over the last 10 years. As a result, users are often surprised to find that a document that renders one way on one system (say, a GitHub wiki) renders differently on another (say, converting to docbook using Pandoc). To make matters worse, because nothing in Markdown counts as a “syntax error,” the divergence often isn’t discovered right away. 
>
>  There’s no standard test suite for Markdown; MDTest is the closest thing we have. The only way to resolve Markdown ambiguities and inconsistencies is Babelmark, which compares the output of 20+ implementations of Markdown against each other to see if a consensus emerges. 
>
> We propose a standard, unambiguous syntax specification for Markdown, along with a suite of comprehensive tests to validate Markdown implementations against this specification. We believe this is necessary, even essential, for the future of Markdown.

**Comment by mitya57** [comment] 2019-07-25 12:59
This is a duplicate of #338. Our official position is in https://github.com/Python-Markdown/markdown/issues/338#issuecomment-54697337, please read that comment for details.

**Closed as completed by mitya57** 2019-07-25 12:59 UTC

**Comment by noraj** [comment] 2019-07-25 13:21
Bye bye compatibility, welcome weird behaviors :slightly_frowning_face:

**Comment by mitya57** [comment] 2019-07-25 13:23
Python-Markdown tries to follow the original Markdown specification where possible, where not possible it follows the Perl Markdown implementation or the other implementations.

If you are looking for a Python CommonMark parser, you can find some on GitHub or on PyPI.

**Comment by facelessuser** [comment] 2019-07-25 13:27
Sometimes there are tradeoffs. Python Markdown favors extensibility over the recent move to standardize every behavior as is done in commonmark.

**Comment by noraj** [comment] 2019-07-25 13:38
> If you are looking for a Python CommonMark parser, you can find some on GitHub or on PyPI.

I agree @mitya57 but mkdocs is using Python-markdown so as python-markdown will never be CommonMark compliant I asked about mkdocs to change of parser https://github.com/mkdocs/mkdocs/issues/1835 but I don't believe it as the core developer @waylan is developing both and will probably never allow it.

**Comment by noraj** [comment] 2019-07-25 13:42
> Sometimes there are tradeoffs. Python Markdown favors extensibility over the recent move to standardize every behavior as is done in commonmark.

True but half-true, [commonmark compliant parser](https://github.com/commonmark/commonmark-spec/wiki/list-of-commonmark-implementations) like [markdown-it](https://github.com/markdown-it/markdown-it) are [extensible](https://github.com/markdown-it/markdown-it#syntax-extensions) and supports [plugins](https://www.npmjs.com/search?q=keywords:markdown-it-plugin) too, allowing to modify the standard behavior. But at least the default is standard and compatible and **known in advance** because every bit of behavior was think and is intended. Non-standard parser have some unexpected, weird and unpredictable bahaviors.

**Comment by facelessuser** [comment] 2019-07-25 13:47
I'm not arguing which is **better**. Python Markdown comes from a time that Commonmark didn't exist and it has legacy baggage and their is no interest to rewrite with so many Commonmark parsers already available. But that doesn't mean there isn't value in this project as they're are many who really on this project. If ever there isn't value, I like most projects, maintainers and users alike will move on.

**Comment by noraj** [comment] 2019-07-25 13:50
> their is no interest to rewrite with so many Commonmark parsers already available

I totally agree.

**Comment by andy0130tw** [comment] 2019-09-11 16:33
Late to the party, but here is my attempt:

https://github.com/andy0130tw/mkdocs-commonmark/commit/bfe0e8a3e183f43f94817f9183509c1e401cbf23

**Comment by rajivm** [comment] 2020-05-17 22:11
Thanks @andy0130tw! Took your fork for CommonMark support and turned it into a plugin: https://github.com/soxhub/mkdocs-plugin-commonmark
