### ISSUE TITLE
markdown footnotes plugins raise TypeError

### ISSUE THREAD

**Issue by a358003542** [Python-Markdown/markdown#1009] opened 2020-08-06 22:16 UTC
It's report that error: 
```
** TypeError: SubElement() argument 1 must be xml.etree.ElementTree.Element, not Element
```

Version 3.1.1 does not have such issue, and if upgrade to 3.2 then will report such error if the markdown content has footnotes.

I have runned  some test and make sure that if i changed the code in `footnotes.py` , changed the `etree` to `util.etree` then , there will be no problem. 

Need to point out this issue is only happened on footnotes plugin and if the markdown content has footnotes, I running on a pelican blog , and there are many other articles that has not footnotes and that has no problem. And also i have noticed some strange behavior , the broken parent element `<Element 0x154545>`  has a short memory address, and other right parent element memory address will be longer than that. i am not sure which is a clue.

**Comment by waylan** [comment] 2020-08-07 14:30
This looks like it could be a duplicate of #950. However, I'm not aware of Pelican using `defusedxml`, unless its being used by a plugin.

**Comment by a358003542** [comment] 2020-08-08 09:49
@waylan I am not sure about the specific reason, but based on my test and compare the version 3.1.1 to 3.2 changes. in the plugin `footnotes.py` the origin code is :

```
from ..util import etree
```
now is 

```
import xml.etree.ElementTree as etree
```
and if i changed the etree to util.etree , because the util.py for some compatible reason which is still has the etree variable. 

then the error disappeared. That's strange problem, but i donot think which is because of `defusedxml` module's problem.

**Comment by waylan** [comment] 2020-08-08 17:14
@a358003542 yes, I know what changes were made. However, those changes would only matter if some other library is modifying the etree library after Markdown imports it but before the footnotes extension is run. Any library that does this is a bad citizen and is responsible for breaking things. We should not need to resort to hacks to make things work. To determine which library is the bad actor, I need to know all plugins you are using and the version of Pelican you are using.

**Comment by a358003542** [comment] 2020-08-08 18:03
@waylan 

my pelican version is 4.2.0 and here is related config:

```
MARKDOWN = {
    'extension_configs': {
        'markdown.extensions.codehilite': {'css_class': 'highlight',
                                           'guess_lang': False},
        'markdown.extensions.toc': {},
        'markdown.extensions.fenced_code': {},
        'markdown.extensions.extra': {},
        'markdown.extensions.meta': {},
        'markdown.extensions.footnotes': {}
    },
    'output_format': 'html5',
}
```

**Comment by waylan** [comment] 2020-08-08 22:04
That tells me which Markdown extensions you are using. But what about Pelican plugins? Markdown works fine by itself and with extensions. It is something related to Pelican which is causing the issue and I'm trying to determine what.

**Comment by a358003542** [comment] 2020-08-09 08:48
@waylan all right, it seems the extract_toc pelican plugin conflicted with this module.  [https://github.com/getpelican/pelican-plugins/blob/master/extract_toc/extract_toc.py](url)

**Comment by a358003542** [comment] 2020-08-09 09:31
@waylan all right. it the pelican plugin pelican_ipynb 's problem. it is the same issue with the #950 . because the nbconvert import issue.

**Comment by a358003542** [comment] 2020-08-09 09:38
@waylan  seems they still not fix this problem, https://github.com/tiran/defusedxml/pull/40/files. i will use the version 3.1.1 to wait they fix this problem.

**Closed as completed** 2020-08-09 20:35 UTC
Labels: duplicate
