### ISSUE TITLE
Help! What wrong with this error?"AttributeError: 'zipimporter' object has no attribute 'exec_module'"

### ISSUE THREAD

**Issue by Cocoooliu** [Python-Markdown/markdown#1488] opened 2024-10-13 17:17 UTC
Sorry I'm new to writing programs and don't know how to fix this error. I'm trying to read and format a document, but I'm running markdown and I'm having this problem.

**Comment by facelessuser** [comment] 2024-10-13 17:23
It is difficult to help as you've given us very little info. This might not even be a problem in a Python Markdown. Can you post a full traceback?

**Comment by Cocoooliu** [comment] 2024-10-13 17:43
I'm sorry if I said anything wrong.
I create a virtual environment to run my code.
![螢幕擷取畫面 2024-10-14 013521](https://github.com/user-attachments/assets/35c91400-e8f4-4ae4-ab4b-32f29016b4a4)

And there is a code to read the data, which contains the code to read the markdown file.
![image](https://github.com/user-attachments/assets/627c3283-47fd-4610-a6a5-a38c53c6fa6d)
![image](https://github.com/user-attachments/assets/0c9b26d0-d92d-4c1a-81c1-2b45a6bdc88b)

But when I run the program, I get this error
![image](https://github.com/user-attachments/assets/e8f783a3-92ba-4e39-a585-e31097edfc28)

I'm sorry for my stupidity.

**Comment by facelessuser** [comment] 2024-10-13 17:49
This might be a duplicate of https://github.com/Python-Markdown/markdown/issues/1132. Unfortunately, I don't think progress has been made on that issue.

**Comment by waylan** [comment] 2024-10-15 14:08
As explained in #1132, this is a bug in Python's standard library, which was fixed in Python 3.10. It appears that you are using Python 3.9. I would suggest updating to Python 3.10 to avoid the issue.

I am closing this as a duplicate.

**Closed as not planned by waylan** 2024-10-15 14:08 UTC
Labels: duplicate
