### ISSUE TITLE
Add support for aliases in wikilinks extension

### ISSUE THREAD

**Issue by kstrauser** [Python-Markdown/markdown#1202] opened 2021-11-22 20:47 UTC
Obsidian supports [wikilinks with aliases](https://help.obsidian.md/How+to/Internal+link#Link+to+headings). For example:

    I called [[Jane Smith|my sister]] today.

would return like "I called _my sister_ today." `markdown` currently doesn't recognize links containing pipe characters, so it doesn't render that example link at all. Could it be updated to support them? Ideally, the alias after the pipe would become the a tag's content, but even using the normal href would be a big improvement. Thanks!

**Comment by waylan** [comment] 2021-11-22 21:22
I'm closing this as a duplicate of #541. Note also my comment in #875 which sums up my view regarding making any changes to the existing wikilinks extension.

Finally, note that there are a few known [third-party][1] wikilink extensions. One of those may meet your needs.

[1]: https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions

**Closed as completed by waylan** 2021-11-22 21:22 UTC
Labels: duplicate
