### ISSUE TITLE
Unexpectedly poor performance with malformed markdown

### ISSUE THREAD

**Issue by andybets** [Python-Markdown/markdown#642] opened 2018-02-21 09:49 UTC
The following takes a long time to process, a timeout option or other mitigation may be needed.
`import markdown`
`a = "[X]( (x)(x)(x)(x)(x)(x)(x)(x)(x)(x)(x)(x)(x)(x)(x)(x)(x)(x)(x)(x)(x)(x)(x)"`
`markdown.markdown(a)`

Obviously the markdown shouldn't be malformed, but since I don't have control of this input, I'd expect it might handle this situation better.

**Comment by facelessuser** [comment] 2018-02-21 13:56
I believe I've already fixed this on master, which should be in the next release. You're welcome to confirm. When I get a chance, I'll confirm myself.

**Comment by waylan** [comment] 2018-02-21 14:18
> a timeout option or other mitigation may be needed.

Actually, Markdown should never raise an error on bad input. That makes it way to easy for untrusted users to crash a server. In fact, that is one of our [stated][1] goals.

[1]: https://python-markdown.github.io/#goals

**Comment by facelessuser** [comment] 2018-02-21 14:21
This doesn't seem to be a problem on master.

**Comment by waylan** [comment] 2018-02-21 14:37
I'm closing this as a duplicate of #161.

**Closed as completed by waylan** 2018-02-21 14:37 UTC
