### ISSUE TITLE
The corner case for smart emphasis and footnotes

### ISSUE THREAD

**Issue by Totktonada** [Python-Markdown/markdown#493] opened 2016-09-13 03:32 UTC
I meet corner case of using smart emphasis with the footnotes extension. Let’s consider example:

```
some text[^1]

[^1]:
    _emphasis works_

    _emphasis doesn't work_
```

The problem appears only with last footnote’s paragraph and when ending undescore is last symbol in the paragraph. As I know footnotes extension appends non-breaking space and a backreference at end of a last paragraph for each footnote. Smart emphasis does `(?!\w)` lookahead (by the way, it’s looks as equial to `\b`) after ending underscore, so non-breaking space, I guess, blocks regex from matching.

The example easy to fix by replacing underscores with stars or by disabling smart emphasis. However, I think, it’s good to be aware of weird corner cases. The issue is informational and has no much impact over me (I’m fallbacks to stars).

**Comment by waylan** [comment] 2016-09-16 22:09
@Totktonada thanks for the report. This is definitely a corner case, but a bug nonetheless. Given the extreme edge that one has to go to to find this and the fact that there is an east workaround, a fix is not terribly high on my priority list. I expect this will be addressed with  the 3.0 refactor. However, a PR would certainly be welcome if anyone wanted to address it before that.

**Comment by facelessuser** [comment] 2017-01-23 15:52
This actually isn't too bad.  Footnotes passes the content above with no newlines at the end of the block.  Simply adding a new line causes it to pass through and emphasis is handled.  I think just inserting a newline when passing any chunk back through the parser is a reasonable solution to this.  It shouldn't have any affect on anything, and it resolves this issue.  No need to wait for 3.0.  I can through together a pull.

**Comment by facelessuser** [comment] 2017-01-23 16:04
It works but then all footnotes have an extra new line in HTML output which isn't ideal as it changes all the tests.  I'll see if I can come up with something that doesn't cause this.

**Comment by waylan** [comment] 2017-01-23 16:15
@facelessuser yes, that has been an annoyance of mine from time to time. If you notice, none of the tests include a newline at the end of the file/ouput (since before I became involved in the project). I have wanted to change this for years, but didn't want to have to update all the tests. In the end, I've always just worked around it.

**Comment by facelessuser** [comment] 2017-01-23 16:17
I found something interesting.  Footnotes is in a list and we send the content.  By setting the parser state to 'list' before parsing chunks.  Everything works:

```py
self.parser.state.set('list')
self.parser.parseChunk(li, self.footnotes[id])
```

I wonder if this would also affect https://github.com/waylan/Python-Markdown/issues/412.

**Comment by facelessuser** [comment] 2017-01-23 16:21
No go for `#412`  but it seems it is sensitive to state.  I would need to play with this more.  Can't promise a clean fix yet.  But I'll see what can be done.

**Comment by facelessuser** [comment] 2017-01-23 17:11
Seems like the first block needs to be parsed as `looselist` and subsequent blocks can get parsed as `list`:

```py
            blocks = self.footnotes[id].split('\n\n')
            if len(blocks) > 1:
                self.parser.state.set('looselist')
                self.parser.parseBlocks(li, blocks[0:1])
                self.parser.state.reset()
                self.parser.state.set('list')
                self.parser.parseBlocks(li, blocks[1:])
                self.parser.state.reset()
            else:
                self.parser.state.set('looselist')
                self.parser.parseBlocks(li, blocks)
                self.parser.state.reset()
```

I would need to test this more, but I think it is possible to fix this.  #412 is a totally different matter and looks like it will be a headache to fix...we'll see if I get to that one.

**Comment by waylan** [comment] 2017-01-23 18:12
Ah, yes, a "looselist" is a list which contains block level children (the name comes from the fact that there is a blank line between list items in the Markdown syntax). Whereas a "list" (which would not contain any blank lines in the Markdown syntax) does not contain any block level elements (the text is a direct child of the `<li>` with no wrapping `<p>` tag). In the case of footnotes, we *always* want a "loose list," even if the footnote is a single paragraph (the text should still get wrapped in a `<p>` tag).

**Comment by facelessuser** [comment] 2017-01-23 18:50
> In the case of footnotes, we always want a "loose list," even if the footnote is a single paragraph (the text should still get wrapped in a <p> tag).

Yes, but it appears you need to switch to 'list' after the first block or things like `_emphasis doesn't work_` break at the end.

I borrowed this idea from the list processor:

```py
            # parse first block differently as it gets wrapped in a p.
            li = util.etree.SubElement(lst, 'li')
            self.parser.state.set('looselist')
            firstitem = items.pop(0)
            self.parser.parseBlocks(li, [firstitem])
            self.parser.state.reset()
```

This still doesn't explain the quirks of #412, but it handles cases like mentioned in the OP. I have a feeling there is something more down the pipe I'm missing which is preventing me from figuring out #412.  But that is not priority to address *this* issue.

**Comment by facelessuser** [comment] 2017-01-23 18:56
I may dig deeper in this and find I'm wrong with the switching to `list`.  I've only looked at this briefly.  I need to double check outputs and make sure I'm not missing anything.

**Comment by waylan** [comment] 2017-01-23 19:23
Keep in mind that in Markdown proper a list can switch back and forth between loose and tight. Like this:

```md
* foo
* bar

* baz
* blah
```

Which ([correctly][1]) results in this output:

```html
<ul>
  <li>foo</li>
  <li>
    <p>bar</p>
  </li>
  <li>
    <p>baz</p>
  </li>
  <li>blah</li>
</ul>
```

Whereas the list of footnotes is a "loose list" throughout the entire list. Just pointing out that there is a difference in desired behavior.

[1]: http://johnmacfarlane.net/babelmark2/?normalize=1&text=*+foo%0A*+bar%0A%0A*+baz%0A*+blah

**Comment by facelessuser** [comment] 2017-01-23 19:32
Thanks.  I'll keep that in mind.  I may just be chasing my tail on this one.  It seems that footnotes path is slightly different then how text normal gets passed down the pipe.  I may end up getting nowhere on this, but I'll see if I can pull something reasonable off.

**Comment by waylan** [comment] 2017-01-23 20:07
Yeah, the footnote extension was the first extension ever created (it was released with the earliest iteration of the extension API). As the API has grown, that extension has been patched time and again. For some time I've felt like it needs to be rebuilt from the ground up to take proper advantage of the current API. As it did not have tests in the beginning, a lot of things that used to work no longer do and we never noticed that we broke them. When we finally created tests, they were incomplete (they miss a bunch of edge cases -- which is apparently what we broke).

**Comment by facelessuser** [comment] 2017-01-23 20:21
That makes a lot of sense.  I think the big issue is the way the footnote div is getting created.  I think if that part gets refactored these issues will go away.  I got some ideas, but I'm not worried if this stuff makes it to the next bug fix release or not.

**Comment by waylan** [comment] 2017-01-23 23:45
Would it make sense to add the NBSP later? Perhaps after inline parsing is complete? Back when the current order of events was set, I doubt we had treeprocessors...

**Comment by facelessuser** [comment] 2017-01-23 23:50
> Would it make sense to add the NBSP later? 

Nah, it's fine.  I was still focused on the newline.  It was more of a symptom. What is actually happening is we have our text `_emphasis_`  and we place a placeholder with `\w` chars `NBSP_PLACEHOLDER = "qq3936677670287331zz"`.  So we get `_empahsis_qq3936677670287331zz`.  We don't do placeholders like this anywhere else in the code, this is why it breaks.  The new line fixes it, but the root cause is that it is a pretty bad placeholder.  If we do `NBSP_PLACEHOLDER = util.STX + "qq3936677670287331zz" + util.ETX`, problem solved.  It is now surrounded by non `\w` chars and `_emphasis_` can be resolved.  It's a one line fix.

EDIT: Ugh typing on phone make this hard.

**Closed as completed** 2017-01-24 03:45 UTC
Labels: bug, extension
