### ISSUE TITLE
Strange data corruption with markdown.extensions.extra

### ISSUE THREAD

**Issue by Lucas-C** [Python-Markdown/markdown#576] opened 2017-08-08 23:16 UTC
Reproduction steps:
```
text = '<!--\nThe first step was to install VisualWorks/Cincom Smalltalk 7.6. The task can be quickly summarized as "Yay ! Let\'s try the venerable SmallTalk !" ...and then...\n<img src="/lucas/wwcb/photos/star_trek_unbelievable.gif" alt="Star Trek Head Hurts">\n\nThere\'s how I managed to do it:\n\n- register a "Personal-Use" license for Cincom Smalltalk [on their website](http://www.cincomsmalltalk.com/main/developer-community/trying-cincom-smalltalk/try-cincom-smalltalk/)\n- download the ISO using the link your received by email\n- extract the ISO content in a directory using the Archive Manager\n- open a console in that directory and `chmod u+x installUnix vw8.0pul/bin/linux86/visual`.\n- launch the installer with `./installUnix`. If you want to specify a custom installation path, select "Custom Install".\n- once you\'ve been through all the graphical installer steps, you\'ll get a pop-up asking you to set an environment variable named `VISUALWORKS` pointing to the installation path. Proceed by defining it in your `.bashrc`.\n\nThen stuck on:\n```\n$ /opt/vw8.0pul/bin/linux86/visual /opt/codecity-image/codecity.im \nVisualWorks(R) 7.5 Non-Commercial Mar 3, 2008\nVisualWorks(R) 7.5 Non-Commercial Mar 3, 2008\nsrc/stack/send.c:317\nFatal error: unexpected translation failure (selector \'value\'), code = 3\n\nSpace could not be allocated.\n```\n'
Markdown(extensions=['markdown.extensions.extra']).convert(text)
```

Output:
```
'<!--\nThe first step was to install VisualWorks/Cincom Smalltalk 7.6. The task can be quickly summarized as "Yay ! Let\'s try the venerable SmallTalk !" ...and then...\n<img src="/lucas/wwcb/photos/star_trek_unbelievable.gif" alt="Star Trek Head Hurts">\n\nThere\'s how I managed to do it:\n\n- register a "Personal-Use" license for Cincom Smalltalk [on their website](http://www.cincomsmalltalk.com/main/developer-community/trying-cincom-smalltalk/try-cincom-smalltalk/)\n- download the ISO using the link your received by email\n- extract the ISO content in a directory using the Archive Manager\n- open a console in that directory and `chmod u+x installUnix vw8.0pul/bin/linux86/visual`.\n- launch the installer with `./installUnix`. If you want to specify a custom installation path, select "Custom Install".\n- once you\'ve been through all the graphical installer steps, you\'ll get a pop-up asking you to set an environment variable named `VISUALWORKS` pointing to the installation path. Proceed by defining it in your `.bashrc`.\n\nThen stuck on:\n\n\x02wzxhzdk:0\x03'
```

If I try to get rid of that extension, or shrink this string more, the problem with the strange `\n\x02wzxhzdk:0\x03\n\n-->` characters at the end vanishes.

I met this issue with `pelican` v3.7.1, which uses Markdown v2.6.8

**Comment by facelessuser** [comment] 2017-08-08 23:43
In the future, I would try and post examples in a Python multi line (triple quoted) strings.  It's hard to tell what is going on in your example.  To figure out what is happening.  After processing this, this is the example:

````
text = '''<!--
The first step was to install VisualWorks/Cincom Smalltalk 7.6. The task can be quickly summarized as "Yay ! Let's try the venerable SmallTalk !" ...and then...
<img src="/lucas/wwcb/photos/star_trek_unbelievable.gif" alt="Star Trek Head Hurts">

There's how I managed to do it:

- register a "Personal-Use" license for Cincom Smalltalk [on their website](http://www.cincomsmalltalk.com/main/developer-community/trying-cincom-smalltalk/try-cincom-smalltalk/)
- download the ISO using the link your received by email
- extract the ISO content in a directory using the Archive Manager
- open a console in that directory and `chmod u+x installUnix vw8.0pul/bin/linux86/visual`.
- launch the installer with `./installUnix`. If you want to specify a custom installation path, select "Custom Install".
- once you've been through all the graphical installer steps, you'll get a pop-up asking you to set an environment variable named `VISUALWORKS` pointing to the installation path. Proceed by defining it in your `.bashrc`.

Then stuck on:
```
$ /opt/vw8.0pul/bin/linux86/visual /opt/codecity-image/codecity.im 
VisualWorks(R) 7.5 Non-Commercial Mar 3, 2008
VisualWorks(R) 7.5 Non-Commercial Mar 3, 2008
src/stack/send.c:317
Fatal error: unexpected translation failure (selector 'value'), code = 3

Space could not be allocated.
```
'''
Markdown(extensions=['markdown.extensions.extra']).convert(text)
````

So first, you have the start of a comment `<!--`, but that never closes.  This is malformed.

Also, the fenced code extension is a preprocessor.  It is not handled inline like many of the other blocks are.  So  the fenced code was converted and a placeholder `\x02wzxhzdk:0\x03` was inserted.  At the end it would normally be replaced with HTML, but in this case, we are dealing with a comment block, which Markdown won't insert converted HTML into.  On top of that, it is malformed.

Personally, I use extensions to strip HTML comments as there should be no need to pass them through, but that is just me. Ideally, one day, Python Markdown will handle fenced blocks inline like other blocks.  It's just tricky due to the current implementation to handle HTML parsing and fenced blocks inline.

**Comment by Lucas-C** [comment] 2017-08-09 01:10
Thanks for the detailed explanation !

Actually it also happens with valid HTML. 
I cannot find a way to properly paste it in Github without messing with **its** Markdown parser :)
But the original HTML comment can be seen on this page: https://chezsoi.org/lucas/blog/2015/03/09/en-how-to-install-codecity-source-code-visualization-tool/

Given that parsing some syntaxically correct Markdown produces an unexpected `\x02wzxhzdk:0\x03` placeholder, I think this qualifies as a bug.

**Comment by waylan** [comment] 2017-08-09 01:57
> Actually it also happens with valid HTML.
I cannot find a way to properly paste it in Github without messing with its Markdown parser 

@Lucas-C simply indent the entire block of text by four spaces and GitHub will see it as a code block and not mess with the formatting.

> produces an unexpected `\x02wzxhzdk:0\x03` placeholder, I think this qualifies as a bug.

I generally agree. However, when you provide invalid input, the output is not necessarily anything you would expect. Without specific "valid" input, its impossible to narrow down the specific edge case. @facelessuser already pointed out the problem with your invalid input. I'm not willing to label this a bug until I see some "valid" input.

**Comment by facelessuser** [comment] 2017-08-09 02:44
I imagine this is a duplicate of https://github.com/waylan/Python-Markdown/issues/458.

**Comment by Lucas-C** [comment] 2017-08-09 07:21
The Common Markdown spec makes it standard to use backticks for fenced blocks:
http://spec.commonmark.org/0.28/#fenced-code-blocks

But I'm OK with the indentation workaround, even if I won't change my habits nor will I modify all my pelican articles that use triple-backticks :)

You can close this if you want

**Comment by waylan** [comment] 2017-08-09 12:42
> I imagine this is a duplicate of #458.

I agree. And as we have not been provided with a simple, clear, valid example, I see no reason to leave this open.

**Closed as completed by waylan** 2017-08-09 12:42 UTC

**Comment by Lucas-C** [comment] 2017-08-10 17:15
Here is a minimal bug reproduction case:

    text = '''
    
    '''
    Markdown(extensions=['markdown.extensions.extra']).convert(text)

**Comment by waylan** [comment] 2017-08-10 17:29
Thanks @Lucas-C, that clarifies that this is in fact a duplicate of #458.

**Comment by facelessuser** [comment] 2017-08-10 17:41
In your specific case @Lucas-C, I'd probably just use an extension to strip out the HTML comments as they serve no real purpose in the final output.  Usually there would be no reason to have that raw syntax in a Markdown file unless it was in a code block.  I get that you are commenting it out since you don't want to use it in this scenario, so as a workaround, there are extensions that can strip the comments, but yes, it is a bug, just not one easily solved at this time due the way raw HTML and fenced code blocks are handled.
