### ISSUE TITLE
Attribute gets attached to the last element of a list, instead of to the list itself.

### ISSUE THREAD

**Issue by JonasOlson** [Python-Markdown/markdown#594] opened 2017-11-05 17:07 UTC
```
- A
- B
{: #best_list }
```

When trying to attach an attribute, as in the code above, to a list (in accordance with the instructions on [attributes for block-level elements](https://pythonhosted.org/Markdown/extensions/attr_list.html#block-level)), the attribute instead gets attached to the `B` list element.

**Comment by waylan** [comment] 2017-11-06 02:05
This is a duplicate of #227.

**Closed as completed by waylan** 2017-11-06 02:05 UTC
