### ISSUE TITLE
Recursive call to toc, other use case

### ISSUE THREAD

**Issue by cbeauchesne** [Python-Markdown/markdown#640] opened 2018-02-20 14:10 UTC
With toc extension, this markdown fails : 

    [toc]
    #[toc]

My guess is that the second toc tag in header in handled, but not the link **inside** the toc

**Comment by waylan** [comment] 2018-02-20 14:32
I'm closing this as a duplicate of #639.

**Closed as completed by waylan** 2018-02-20 14:32 UTC

**Comment by cbeauchesne** [comment] 2018-02-20 14:33
Ok, but be carefull, it's the same consequence, but not the same root cause.
