### ISSUE TITLE
Bug in "md_in_html" extension leading to invalid wrapping in <p></p> tags

### ISSUE THREAD

**Issue by fladd** [Python-Markdown/markdown#1018] opened 2020-08-27 15:52 UTC
This:
```html
<figure markdown="1">

![cat](http://i.imgur.com/NUyttbn.gif)
<figcaption>**Figure 1.** Heavy breathing cat. And here comes a rather long descrition to test wrapping and stuff.</figcaption>

</figure>
```

After conversion with:
```python
markdown.markdown(text, extensions=['markdown.extensions.md_in_html'])
```

Leads to this:
```html
<figure>
<p><img alt="cat" src="http://i.imgur.com/NUyttbn.gif"/>
<figcaption><strong>Figure 1.</strong> Heavy breathing cat. And here comes a rather long description to test wrapping and stuff.</figcaption></p>
</figure>
```

Which is invalid HTML, because there cannot be `<p></p>` tags within a `<figure>` tag.

**Comment by waylan** [comment] 2020-08-27 22:38
In addition to `markdown="1"` there is also `markdown="span"` and `markdown="block"` which force the content to be either parsed as span level or block level. By default, `markdown="1"` results in the content of the following tags being parsed as `span`: `p`, `h[1-6]`, `li`, `dd`, `dt`, `td`, `th`, `legend`, and `address` (all other block-level tags get parsed as `block`). In other words, none of the raw tags in that list will have block level tags inserted in them. Sounds like you are saying `figure` should be added to that list.

Interestingly, in #803 we are in the process of completely replacing the raw HTML parsing code. List list of tags has been updated as follows:

https://github.com/waylan/markdown/blob/183537fbd17b357a375979717934d1b09e2cf2f1/markdown/extensions/md_in_html.py#L27-L38

It appears that `figure` is explicitly in the `block` list. Can you point to where the HTML spec indicates that this is not valid?

In the meantime, you can use `<figure markdown="span">` as a workaround until we address this.

**Comment by waylan** [comment] 2020-08-28 13:23
I checked the [spec][1] and don't see anything which expressly states that `<p>` tags are not valid inside of a `<figure>` tag. In fact, the fourth example actually shows a `<p>` tag inside a `<figure>` tag:

> Here, a part of a poem is marked up using figure.
> 
> ```html
> <figure>
>  <p>'Twas brillig, and the slithy toves<br>
>  Did gyre and gimble in the wabe;<br>
>  All mimsy were the borogoves,<br>
>  And the mome raths outgrabe.</p>
>  <figcaption><cite>Jabberwocky</cite> (first verse). Lewis Carroll, 1832-98</figcaption>
> </figure>
> ```

That said, I could see an argument for having the default to be `span` rather than `block`. In the cases where the document author actually wants `block`, then they can set `markdown="block"`.

However, I'm inclined to leave the default as-is. Whenever you don't want `<p>` tags simply use `markdown="span"`.

[1]: https://html.spec.whatwg.org/multipage/grouping-content.html#the-figure-element

**Comment by waylan** [comment] 2020-08-28 13:50
So I took a closer look at the example provided above with is showing invalid output. It is, in fact, invalid, because the `<p>` tag wraps both the `<img>` and the `<figcaption>` tags. It should only wrap the image. However, that is caused by badly formed Markdown. Add a blank line between the `<img>` and the `<figcaption>` and the `<p>` no longer wraps the `<figcaption>`. In other words this:

```
<figure markdown="1">

![cat](http://i.imgur.com/NUyttbn.gif)

<figcaption>**Figure 1.** Heavy breathing cat. And here comes a rather long descrition to test wrapping and stuff.</figcaption>

</figure>
```

renders as

```
<figure>
<p><img alt="cat" src="http://i.imgur.com/NUyttbn.gif" /></p>
<figcaption>**Figure 1.** Heavy breathing cat. And here comes a rather long descrition to test wrapping and stuff.</figcaption>
</figure>
```

And that is valid HTML.

I'm closing this as wontfix.

**Closed as completed by waylan** 2020-08-28 13:50 UTC
Labels: extension, wontfix
