### ISSUE TITLE
Option to avoid automatic hyperlinking of URLs inside fenced code blocks would be useful

### ISSUE THREAD

**Issue by simonw** [Python-Markdown/markdown#1146] opened 2021-06-19 17:13 UTC
I ran into a problem where the following fenced code block:
````
```
$ curl -s 'https://api.github.com/users/dogsheep/repos'\
  | sqlite-utils memory - '
      select full_name, forks_count, stargazers_count
      from stdin order by stargazers_count desc limit 5
    ' -t
[...]
$ sqlite-utils memory species.csv creatures.csv '
  select * from creatures join species on creatures.species_id = species.id
'
````
Was being rendered with both `https://api.github.com/users/dogsheep/repos` and `species.id` (in the SQL query) as links. `species.id` isn't intended as a link, and the `curl -s` link became `https://api.github.com/users/dogsheep/repos'` - note the trailing `'` character - which was a 404.

<img width="646" alt="Banners_and_Alerts_and_Datasette__An_open_source_multi-tool_for_exploring_and_publishing_data" src="https://user-images.githubusercontent.com/9599/122650292-e18b7280-d0e6-11eb-8052-0da24f44cf6e.png">

I came up with a workaround https://github.com/simonw/datasette.io/issues/66#issuecomment-864437178 where I used BeautifulSoup to strip any links that occurred inside a `<pre>` tag, but it would be great if there was an option for the `fenced_code` to disable auto-linking of content inside the rendered blocks.

**Comment by waylan** [comment] 2021-06-19 22:26
This should definitely not be happening. What options are you passing to Python-Markdown?

**Comment by waylan** [comment] 2021-06-29 14:17
First of all, Python-Markdown does not autolink any URLs. Autolinks must be wrapped in angle brackets. This suggests to me that a third party extension must be involved. As insufficient information has been provided to replicate the described behavior, I am closing this. Of course, if this is caused by a third party extension, the matter should be addressed by that extension.

**Closed as completed by waylan** 2021-06-29 14:17 UTC
Labels: more-info-needed

**Comment by simonw** [comment] 2022-02-26 18:08
My apologies: it turns out this was cased by the way I was using Bleach: https://bleach.readthedocs.io/en/latest/linkify.html#skipping-links-in-specified-tag-blocks-skip-tags
