### ISSUE TITLE
How to add an attribute list to a table?

### ISSUE THREAD

**Issue by andreas-h** [Python-Markdown/markdown#505] opened 2016-10-21 14:34 UTC
I'd like to add an attribute list to a table.  However, when I do this:

```
Head 1 | Head 2
-------|----
Phone  | 123
E-mail | bla@blupp
Room   | 321
{: style=" margin-right: 20px; margin-left: 0px; float: left; width: 240px;"}
```

the attribute list gets applied to the last `<td>` element, not to the table.

How can I apply an attribute list to the `<table>` element?

**Comment by waylan** [comment] 2016-10-21 15:16
This is a duplicate of #312. A complete explanation of why this is not supported is provided there.

**Closed as completed by waylan** 2016-10-21 15:16 UTC
