### ISSUE TITLE
AttributeError: 'zipimporter' object has no attribute 'exec_module'

### ISSUE THREAD

**Issue by p0las** [Python-Markdown/markdown#1319] opened 2023-02-07 00:14 UTC
in certain python environments (foundry nuke python 3.9.10) markdown fails to import with:

File "site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "site-packages\markdown\__init__.py", line 22, in <module>
    from .core import Markdown, markdown, markdownFromFile
  File "site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "site-packages\markdown\core.py", line 27, in <module>
    from .preprocessors import build_preprocessors
  File "site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "site-packages\markdown\preprocessors.py", line 29, in <module>
    from .htmlparser import HTMLExtractor
  File "site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "site-packages\markdown\htmlparser.py", line 31, in <module>
    spec.loader.exec_module(htmlparser)
AttributeError: 'zipimporter' object has no attribute 'exec_module'

we have downgraded markdown to 3.1.1 and this fixed the issue.
we actually don't know if the problem is on the foundry side or markdown package. reporting here in case other ppl have similar issues.

**Comment by mitya57** [comment] 2023-02-07 07:21
I think it's a bug in pyside2/shiboken, not in Python-Markdown.

I have seen something similar when packaging pyside2 for Debian. I ended up using this patch from ArchLinux which solved all import problems. Maybe it will help for you too: https://github.com/archlinux/svntogit-packages/blob/packages/pyside2/trunk/fix-build.patch

**Comment by waylan** [comment] 2023-02-08 13:56
I am closing this as a duplicate of #1132.

**Closed as not planned by waylan** 2023-02-08 13:56 UTC
Labels: duplicate
