### ISSUE TITLE
markdown changes content inside <script> tag

### ISSUE THREAD

**Issue by schlichtanders** [Python-Markdown/markdown#1411] opened 2023-11-09 16:41 UTC
concretely, a `>` is replaced with `&gt;` which of course makes the <script> tag unusable

**Comment by facelessuser** [comment] 2023-11-09 16:51
Can you provide a minimal, reproducible example of how you are including script tags in your Markdown?

**Comment by waylan** [comment] 2023-11-09 20:24
Note that the [Markdown rules](https://daringfireball.net/projects/markdown/syntax#html) state:

> The only restrictions are that block-level HTML elements — e.g. `<div>`, `<table>`, `<pre>`, `<p>`, etc. — must be separated from surrounding content by blank lines, and the start and end tags of the block should not be indented with tabs or spaces. 

And yes, a `<script>` tag is included in the list of "block-level HTML elements" although not specifically listed there in the rule. If you are following that rule and still getting the described behavior, then you will need to provide an example as requested. Please provide the input, the output you are getting, the output you expect and any options you may be passing to Markdown.

**Comment by waylan** [comment] 2024-01-12 15:02
I am closing this due to a lack of information. If a reproducible example can be provided, then we will reconsider.

**Closed as not planned by waylan** 2024-01-12 15:02 UTC
Labels: more-info-needed
