### ISSUE TITLE
TOC fails

### ISSUE THREAD

**Issue by pharos-alexandria** [Python-Markdown/markdown#1010] opened 2020-08-08 17:26 UTC
When I try this (in python3.8):
```

text = '''
[TOC]

# Some Header

## Next Level

'''
md = markdown.Markdown(extensions=["toc"])
html = md.convert(text)
```
it fails with
```
~/venv/lib/python3.8/site-packages/markdown/extensions/toc.py in replace_marker(self, root, elem)
    191                 for i in range(len(p)):
    192                     if p[i] == c:
--> 193                         p[i] = elem
    194                         break
    195 

TypeError: expected an Element, not "Element"
```

Is there a bug or am I doing something wrong?

**Comment by facelessuser** [comment] 2020-08-08 18:02
I think there is something different in your environment. Can you give more info about your environment? OS, is this in Anaconda vs a normal install, stuff like that.

```py
Python 3.8.3 (default, May 27 2020, 20:54:22)                                                                                                                                        
[Clang 11.0.3 (clang-1103.0.32.59)] on darwin                                                                                                                                        
Type "help", "copyright", "credits" or "license" for more information.                                                                                                               
>>> text = '''
... [TOC]
... 
... # Some Header
... 
... ## Next Level
... 
... '''
>>> import markdown
>>> md = markdown.Markdown(extensions=["toc"])
>>> html = md.convert(text)
>>> print(html)
<div class="toc">                                                                                                                                                                    
<ul>                                                                                                                                                                                 
<li><a href="#some-header">Some Header</a><ul>                                                                                                                                       
<li><a href="#next-level">Next Level</a></li>                                                                                                                                        
</ul>                                                                                                                                                                                
</li>                                                                                                                                                                                
</ul>                                                                                                                                                                                
</div>                                                                                                                                                                               
<h1 id="some-header">Some Header</h1>                                                                                                                                                
<h2 id="next-level">Next Level</h2>     
```

**Comment by pharos-alexandria** [comment] 2020-08-08 20:08
It's Fedora 32. 

In Python console it works:
``` python
Python 3.8.5 (default, Jul 20 2020, 00:00:00) 
[GCC 10.1.1 20200507 (Red Hat 10.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> text = '''
... [TOC]
... 
... # Some Header
... 
... ## Next Level
... 
... '''
>>> import markdown
>>> md = markdown.Markdown(extensions=["toc"])
>>> html = md.convert(text)
>>> print(html)
<div class="toc">
<ul>
<li><a href="#some-header">Some Header</a><ul>
<li><a href="#next-level">Next Level</a></li>
</ul>
</li>
</ul>
</div>
<h1 id="some-header">Some Header</h1>
<h2 id="next-level">Next Level</h2>
>>> 

```
But it does **not** work with jupyter lab (2.1.0) within the same virtual environment.

**Comment by facelessuser** [comment] 2020-08-08 21:49
Sounds like you have a jupyter issue. This would appear to be a duplicate of https://github.com/Python-Markdown/markdown/issues/950.

**Comment by pharos-alexandria** [comment] 2020-08-10 08:32
But it seems nonetheless to be a different case, as nbconvert is not involved here, I'm only executing code inside the notebook. (If I understand #950 correctly.)

**Comment by waylan** [comment] 2020-08-10 19:53
#950 occurs simply by having `defuesxml` imported. It does not need to be called. Therefore, if you are using Markdown within a notebook, Jupiter Notebook has already imported is dependencies and the problem will exist. The good news is that `defusedxml` appears to have a fix in the works.

**Closed as completed** 2020-09-17 12:51 UTC
Labels: duplicate
