### ISSUE TITLE
How to apply attribute to a list?

### ISSUE THREAD

**Issue by GrantEdwards** [Python-Markdown/markdown#912] opened 2020-02-17 18:22 UTC
I want to created a 'lettered' ordered list, so I tried to use the attr_list extension to apply the type='a' attribute to an ordered list, but nothing I try works.  Either the attribute list line is shown in the output or it's applied to something else.   What is the syntax to apply an attribute list to an ordered list?

**Comment by waylan** [comment] 2020-02-17 22:32
This appears to be a duplicate of #227.

**Comment by GrantEdwards** [comment] 2020-02-17 22:51
My apologies — it is indeed a duplicate of #227

**Closed as completed** 2020-02-18 03:42 UTC
