### ISSUE TITLE
Extended code block with pound-sign comments renders incorrectly

### ISSUE THREAD

**Issue by slbayer** [Python-Markdown/markdown#843] opened 2019-07-05 18:34 UTC
I'm using Python-markdown 3.1.1 on Python 3.7.3. 

The following Markdown snippet renders as expected in the previewer here, and I can't find anything wrong with it Markdown-wise. I'm embedding it here and attaching it for convenience as a file.

````
The template for the Web application configuration file is found in
```minimal_example/settings.config.in```. It looks like this:

```
# Copy this file to settings.config. It is used by the Web server. It
# is a Python config file.

# If you need a special version of Java, specify it here. Otherwise,
# the default Java executable in your path will be used.
# JAVABIN =
# If you want a default heap size, specify it here.
# HEAP_SIZE =
# If you want a default stack size, specify it here.
# STACK_SIZE =
```
````

[sample.txt](https://github.com/Python-Markdown/markdown/files/3363721/sample.txt)

My expectation is that the section of pound-sign quotes would be rendered as a ```<code> ``` block in HTML, but instead, I get this:

```
<p>The template for the Web application configuration file is found in\n<code>minimal_example/settings.config.in</code>. It looks like this:</p>
<p>```</p>
<h1>Copy this file to settings.config. It is used by the Web server. It</h1>
<h1>is a Python config file.</h1>
<h1>If you need a special version of Java, specify it here. Otherwise,</h1>
<h1>the default Java executable in your path will be used.</h1>
<h1>JAVABIN =</h1>
<h1>If you want a default heap size, specify it here.</h1>
<h1>HEAP_SIZE =</h1>
<h1>If you want a default stack size, specify it here.</h1>
<h1>STACK_SIZE =</h1>
<p>```</p>
```

**Comment by facelessuser** [comment] 2019-07-05 18:38
What extensions do you have enabled? If you are expecting ```` ``` ```` to render a block of text (not inline) as a code, this will not occur without the `fenced_code` extension.

**Comment by waylan** [comment] 2019-07-05 19:14
This appears to be a duplicate of #842.  As a reminder, fenced code blocks are not part of standard Markdown and therefore are not enabled by default.

Also, I've edited the original post to properly use code blocks.

**Closed as completed by waylan** 2019-07-05 19:14 UTC
