### ISSUE TITLE
Heading within a list is not rendered as expected

### ISSUE THREAD

**Issue by rs2** [Python-Markdown/markdown#481] opened 2016-06-09 10:33 UTC
I.e. 
`* ## Foobar`
Is expected to be an H2 bullet point.

**Comment by waylan** [comment] 2016-06-09 12:37
I'm getting:

``` html
<ul>
  <li>
    <h2>Foobar</h2>
  </li>
</ul>
```

Which is correct. What are you getting and which version are you using?

**Comment by waylan** [comment] 2016-10-17 21:58
I'm closing this due to an inability to reproduce and/or a lack of information.

**Closed as completed by waylan** 2016-10-17 21:58 UTC

**Comment by rs2** [comment] 2016-10-18 07:43
:+1:
