### ISSUE TITLE
Underscore is not getting converted to <em> tag if &nbsp; present

### ISSUE THREAD

**Issue by Arushi2012** [Python-Markdown/markdown#1226] opened 2022-02-27 12:25 UTC
markdown version used : 3.3.6

String: hello\&nbsp;\_\&nbsp;bye\&nbsp;\_

Expected output: hello _bye_

Observed output: hello _ bye _

**Comment by waylan** [comment] 2022-02-28 15:09
At first I was going to suggest that this behavior is caused by our [middle-word emphasis][1] policy, that you could can use the [Legacy EM extension][2] to restore the original behavior; and that I would simply fall back to raw HTML as a workaround: `hello&nbsp;<em>&nbsp;bye&nbsp;</em>`.

However, I tested things and I can't replicate the behavior you describe. It is working fine for me.

```python
>>> import markdown
>>> markdown.version
'3.3.6'
>>> markdown.markdown('hello&nbsp;_&nbsp;bye&nbsp;_')
'<p>hello&nbsp;<em>&nbsp;bye&nbsp;</em></p>'
```

[1]: https://python-markdown.github.io/#differences
[2]: https://python-markdown.github.io/extensions/legacy_em/

**Comment by waylan** [comment] 2022-05-05 13:59
I'm closing this due to the inability to replicate. If more information is provided in the future so that the problem can be replicated, we will reopen the issue.

**Closed as completed by waylan** 2022-05-05 13:59 UTC
Labels: more-info-needed, invalid
