### ISSUE TITLE
How to add attributes to an entire list or definition list?

### ISSUE THREAD

**Issue by hanwentao** [Python-Markdown/markdown#600] opened 2017-11-18 16:15 UTC
This issue is about the combination usage of the extension *attribute list* with the built-in list or the extension *definition list*.  How to add an attribute to the entire list, instead of merely an item?  The following code doesn't work (the attribute is applied to the second item):
```
* a
* b
{: .list}
```

**Comment by waylan** [comment] 2017-11-20 20:58
This is a duplicate of #227.

**Closed as completed by waylan** 2017-11-20 20:58 UTC
