### ISSUE TITLE
Provide option to dump parse tree as JSON

### ISSUE THREAD

**Issue by gvwilson** [Python-Markdown/markdown#807] opened 2019-03-18 11:14 UTC
The Kramdown parser can dump its parse tree as JSON for debugging and to make it easy for people to write style checkers for Markdown (e.g., to run as Travis jobs). For example, running this script:

```
require "kramdown"
require "json"

markdown = STDIN.read()
doc = Kramdown::Document.new(markdown)
tree = doc.to_hash_a_s_t
puts JSON.pretty_generate(tree)
```

with this input:

```
# Title
paragraph

- list
- list
```

produces this JSON:

```
{
  "type": "root",
  "options": {
    "encoding": "UTF-8",
    "location": 1,
    "options": {
    },
    "abbrev_defs": {
    },
    "abbrev_attr": {
    }
  },
  "children": [
    {
      "type": "header",
      "options": {
        "level": 1,
        "raw_text": "Title",
        "location": 1
      },
      "children": [
        {
          "type": "text",
          "value": "Title",
          "options": {
            "location": 1
          }
        }
      ]
    },
    {
      "type": "p",
      "options": {
        "location": 2
      },
      "children": [
        {
          "type": "text",
          "value": "paragraph",
          "options": {
            "location": 2
          }
        }
      ]
    },
    {
      "type": "blank",
      "value": "\n"
    },
    {
      "type": "ul",
      "options": {
        "location": 4
      },
      "children": [
        {
          "type": "li",
          "options": {
            "location": 4
          },
          "children": [
            {
              "type": "p",
              "options": {
                "location": 4,
                "transparent": true
              },
              "children": [
                {
                  "type": "text",
                  "value": "list",
                  "options": {
                    "location": 4
                  }
                }
              ]
            }
          ]
        },
        {
          "type": "li",
          "options": {
            "location": 5
          },
          "children": [
            {
              "type": "p",
              "options": {
                "location": 5,
                "transparent": true
              },
              "children": [
                {
                  "type": "text",
                  "value": "list",
                  "options": {
                    "location": 5
                  }
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

It would be useful to have this as an option for Python-Markdown: is the best way to implement it to add it as an output format, or to break the `convert` function in `core.py` in half near the statement `output = self.serializer(root)` so as to avoid running text post-processors on the JSON?

(Note: I can build the checker I need by generating HTML, parsing it, and then walking the DOM, but (a) serializing only to re-parse seems clumsy and (b) location information in the original Markdown is lost.)

**Comment by waylan** [comment] 2019-03-18 13:18
This is mostly a duplicate of #420.  Specifically, [this comment][1] explains the decision we made for version 3.0. 

While one could override the serializer, be aware that the serializer does not output a complete document. There are still postprocessors which finalize the conversion and those postprocessors specifically expect HTML. Therefore, you would need to replace each of those in addition to the serializer.

Finally, you may find [lepture/mistune][2] better meets your needs.

I'm closing this as a duplicate.

[1]: https://github.com/Python-Markdown/markdown/issues/420#issuecomment-407850147
[2]: https://github.com/lepture/mistune

**Closed as completed by waylan** 2019-03-18 13:18 UTC
Labels: duplicate
