### ISSUE TITLE
Simpler syntax for regular HTTP, HTTPS URLS; how to start?

### ISSUE THREAD

**Issue by AnneTheAgile** [Python-Markdown/markdown#393] opened 2015-03-08 00:06 UTC
hi! I'm  happy to have found you via the MkDocs project via Docker/docs. 
I am quite unhappy with the normal [1] syntax for making hotlinks, which requires wrapping a link with angle brackets. Do I understand it correctly that to get a 'fix' for this all I would need to do is to write my own extension and then I could import and use it?
Can you point me to a simple extension example?
thank you!
AnneTheAgile

1.[] ; ; ; ; ; ; ; ; ; ;  X.Python-Markdown/auto-links.txt at master · waylan/Python-Markdown ; ; https://github.com/waylan/Python-Markdown/blob/master/tests/basic/auto-links.txt

**Comment by erez-o** [comment] 2015-03-08 02:32
If I understand you correctly, you want all links to automatically be linkable regardless of angle brackets.

Though it appears in github flavored markdown, it does not appear in the standard markdown.

A practical solution I use, is to use the package bleach - it has 2 functions - one that cleans evil scripts, and the other, linkify, that creates auto links.

Hope this helps

**Comment by facelessuser** [comment] 2015-03-08 02:54
I've written a number of extensions that I am still considering in beta state, but one of them auto-links web and email links: https://github.com/facelessuser/pymdown-extensions/blob/master/pymdownx/magiclink.py.  I am sure there are others as well.  Bleach also sounds like a good option.

Documentation here: http://facelessuser.github.io/PyMdown/Extensions/MagicLink.html.  I generate the documents with the the extensions to demonstrate how they work.

**Comment by waylan** [comment] 2015-03-09 00:26
@AnneTheAgile thank you for your request. However, as this is not a part of Markdown's standard syntax, I have no interest in implementing something like this myself. Of course, we offer an extension [API](https://pythonhosted.org/Markdown/extensions/api.html) which allows anyone to implement whatever they want.

First, I would suggest you look around to see if someone has already built what you want. A few commenters have already pointed you at their solutions. You might find something else in the list of known [third-party extensions](https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions).

If you elect to build your own, you may find this [tutorial](https://github.com/waylan/Python-Markdown/wiki/Tutorial:-Writing-Extensions-for-Python-Markdown) may get you started. That said, I've never seen an implementation that always correctly identified urls within the text. there is always a few edge cases that result in either false negatives or false positives. For that reason, I think requiring that all URLs must have markup identifying them as such was the right way to go. Of course, that is just my personal opinion. You are free to disagree and implement what you want.

As this is not a bug report. I am closing this. If you would like assistance in building an extension (or any other non bug report discussions), please take those discussions to the [mailing list](http://lists.sourceforge.net/lists/listinfo/python-markdown-discuss).

**Closed as completed by waylan** 2015-03-09 00:26 UTC

**Comment by AnneTheAgile** [comment] 2015-03-09 03:12
ty so much everyone for all your feedback! I will try out your ideas.
