### ISSUE TITLE
markdown.extensions.footnotes -- multiple references to the same footnote generate duplicate HTML IDs

### ISSUE THREAD

**Issue by a3nm** [Python-Markdown/markdown#468] opened 2016-04-09 09:27 UTC
Consider the following minimal Markdown document which contains two references to the same footnote:

``` markdown
[^a][^a]

[^a]: b
```

I compile it to HTML with Python-Markdown with the following code:

``` python
#!/usr/bin/python3

import markdown
markdown.markdownFromFile("minimal.md", "minimal.html",
        extensions=['markdown.extensions.footnotes'])
```

The result is the following:

``` html
<p><sup id="fnref:a"><a class="footnote-ref" href="#fn:a" rel="footnote">1</a></sup><sup id="fnref:a"><a class="footnote-ref" href="#fn:a" rel="footnote">1</ a></sup></p>
<div class="footnote">
<hr />
<ol>
<li id="fn:a">
<p>b&#160;<a class="footnote-backref" href="#fnref:a" rev="footnote" title="Jump back to footnote 1 in the text">&#8617;</a></p>
</li>
</ol>
</div>
```

This HTML is invalid (and will be rejected by validators) because the ID "fnref:a" is multiply defined.

The footnotes extensions has a parameter `UNIQUE_IDS` which looks related (though the description is not very clear), but it does not appear to work for this purpose. If I set it to true as follows:

``` python
#!/usr/bin/python3

import markdown
markdown.markdownFromFile("minimal.md", "minimal_param.html",
        extensions=['markdown.extensions.footnotes(UNIQUE_IDS=True)'])
```

I obtain the following output:

``` html
<p><sup id="fnref:2-a"><a class="footnote-ref" href="#fn:2-a" rel="footnote">1</a></sup><sup id="fnref:2-a"><a class="footnote-ref" href="#fn:2-a" rel="footnote">1</a></sup></p>
<div class="footnote">
<hr />
<ol>
<li id="fn:2-a">
<p>b&#160;<a class="footnote-backref" href="#fnref:2-a" rev="footnote" title="Jump back to footnote 1 in the text">&#8617;</a></p>
</li>
</ol>
</div>
```

This time, the duplicate ID is "fnref:2-a", but the problem remains.

I think Python-Markdown should be generating different HTML IDs for the different invocations of the same footnote, with the backlink pointing, e.g., to the first one, or (ideally) offering backlinks to all of them as Wikipedia does (see https://en.wikipedia.org/wiki/Help:Footnotes#Footnotes:_using_a_source_more_than_once).

**Comment by waylan** [comment] 2016-04-11 13:09
I admit, this use case is not accounted for in the extension. As this extension is a clone of PHP Markdown's Extra's [footnote](https://michelf.ca/projects/php-markdown/extra/#footnotes) implementation, I was curious what that does (using your sample input):

``` html
<p><sup id="fnref:a"><a href="#fn:a" class="footnote-ref">1</a></sup><sup id="fnref2:a"><a href="#fn:a" class="footnote-ref">1</a></sup></p>

<div class="footnotes">
<hr />
<ol>

<li id="fn:a">
<p>b&#160;<a href="#fnref:a" class="footnote-backref">&#8617;&#xFE0E;</a> <a href="#fnref2:a" class="footnote-backref">&#8617;&#xFE0E;</a></p>
</li>

</ol>
</div>
```

The issue is the back-reference link. If you have two references to the footnote, which one does the back-reference link point to? The PHP lib adds two back-reference links to the footnote, whereas we assign both references the same ID (with only one back-reference link). Clearly we are doing it wrong as we are generating invalid HTML.

BTW, the `UNIQUE_IDS` setting refers to the ID of the footnote, not the back-reference. Suppose you have multiple documents on one page (imagine the home page of a blog) and each document has a footnote: `[^1]`. This setting ensures that each footnote is assigned unique IDs. As the back-reference ID is built off of the footnote's ID, ensuring that the footnote ID is unique is enough to ensure everything is unique as long as each footnote is only referenced once. Unique reference IDs need to happen regardless of the `UNIQUE_IDS` setting simply to avoid invalid HTML within a single document.

**Comment by mitya57** [comment] 2016-04-25 13:56
FWIW, +1 for copying PHP Markdown Extra's (and Wikipedia's) behavior: inserting multiple back-reference links to the footnote if there were multiple references to it.

**Comment by facelessuser** [comment] 2017-01-22 19:42
I'm actually working on a fix for this and should have it ready soon.  I'm picking up some of the low hanging fruit.

**Closed as completed** 2017-01-23 19:31 UTC
Labels: bug, extension

**Comment by a3nm** [comment] 2017-02-18 11:56
I just tested this out. It works fine for my purposes. Now my markup is valid again. :)

Thanks a lot for taking the time to fix this!
