### ISSUE TITLE
Empty first cell in a table

### ISSUE THREAD

**Issue by vincentbernat** [Python-Markdown/markdown#635] opened 2018-01-31 07:07 UTC
Hey!

With Markdown 2.6.8, I was able to have an empty first cell by using a non-breakable space. With 2.6.11, this doesn't work anymore. I can use a zero width non-breaking space instead but I fear I would forget it about after some time. Instead, I am using `<i></i>`. But maybe there should be a cleaner way?

```markdown
<i></i>       | 1 core  | 2 cores | 4 cores | 6 cores
------------- | ------- | ------- | ------- | -----------------
CPU 1, Core 1 | network | network | network | network + haproxy
CPU 1, Core 2 | haproxy | haproxy | haproxy | TLS
CPU 1, Core 3 | TLS     | TLS     | TLS     | TLS
CPU 1, Core 4 | -       | TLS     | TLS     | TLS
CPU 2, Core 5 | -       | -       | network | TLS
CPU 2, Core 6 | -       | -       | TLS     | TLS
CPU 2, Core 7 | -       | -       | TLS     | TLS
CPU 2, Core 8 | system  | system  | system  | system + haproxy
```

**Comment by facelessuser** [comment] 2018-01-31 07:24
There was a recent rework in to improve table handling. I guess one of the side effects is that I added calls to `strip()` in a couple of places, but that will strip out things like non-breaking spaces.  If all we want to strip is spaces, we could change it to a less aggressive stripping.  I'd be interested to hear @waylan's thoughts on it.

Edit: Specifically, we could just call `.strip(' ')` which would strip only spaces.

**Comment by waylan** [comment] 2018-01-31 14:18
@vincentbernat, have you tried using an HTML entity? As the output is HTML, you really should be using an HTML entity, not the Unicode character. I realize that you were using a *zero length* char, but what's wrong with a single width non-breaking space (`&nbsp;`)? The column will always be wider than that anyway due to the other rows.

> Specifically, we could just call `.strip(' ')` which would strip only spaces.

I'm of two minds about this. If someone is inserting something other than a normal space, then it is probably intentional and maybe we should leave it. Of course, there are those annoying cases where a user copy and pastes something not realizing they copied something other than a normal space char. In that scenario the current behavior is better. But the current behavior limits those who know what they are doing. However, users should be using HTML entities, not various Unicode chars... I can go back and forth all day.

I suppose in the end, as the current behavior was an unintentional behavioral change, we should probably change it back.

**Comment by facelessuser** [comment] 2018-01-31 14:26
Cool, I was kind of on the fence about it myself which is why I asked. The change is trivial, so I can throw together pull.

So this will be fixed, but in the short term, the answer is to use an HTML entity like `&nbsp;`.

**Comment by waylan** [comment] 2018-01-31 14:33
If you really want a zero-width non-breaking space, which doesn't have an HTML entity, as with all Unicode chars you can use a character reference: `&#xfeff;` or `&#65279;`.

**Comment by vincentbernat** [comment] 2018-01-31 19:37
All the proposed workarounds are fine for me. I just need the empty cell. Maybe, this could just be documented (instead of just reverting to the previous behavior which was not more intuitive): this would enable people looking into a solution to this problem to know they can insert any blank HTML entity. I can do a PR for that if needed.

**Comment by facelessuser** [comment] 2018-01-31 20:29
Even though I'm okay on one hand with the new process stripping non-breaking spaces, on the other hand, it may be *more* correct to strip only normal spaces.

I personally think it always makes more sense to use something visually distinguishable from a space.  Whether you use entities, or a short hand like [some extensions](https://facelessuser.github.io/pymdown-extensions/extensions/escapeall/) allow. Using a real non-breaking space in a file can easily be viewed as a normal space if your editor isn't distinguishing them somehow.

I'll probably still create the pull to prevent stripping of non-space characters as it is easy to do, and wasn't initially my intention change the behavior, but I'll let @waylan speak for whether he feels it necessary to show examples for empty cells.

**Comment by waylan** [comment] 2018-01-31 20:34
So I just looked at this again and questioned why we can't  just use normal spaces for an empty cell. Of course, you can, except for the first cell of the table header row. That cell *must* start with a non-white-space character, which is consistent  with the reference implementation (PHP Markdown Extra). Conveniently, Markdown does not treat HTML entities as white-space characters.

In any event, I don't see what we need to document. For any white-space character except a normal space char, you should always use HTML entities. That is just good practice for Markdown text in general and not specific to tables.

Regardless, we should revert the change in behavior for the simple reason that its a regression that potentially breaks existing documents. If the current behavior had always existed, then I would say to leave it.

**Closed as completed** 2018-02-22 13:46 UTC
