### ISSUE TITLE
Add language as class to highlighted code block

### ISSUE THREAD

**Issue by stefanv** [Python-Markdown/markdown#463] opened 2016-03-18 00:28 UTC
A patch is given here:

https://blog.liang2.tw/posts/2016/02/markdown-codehilite-lang/

**Comment by waylan** [comment] 2016-03-18 01:53
Our code highlighter returns the exact output of Pygments. I see no need to change that. I'd need to see a pretty persuasive argument, especially given that in all the years this extension has existed, no one has ever made such a request before.

**Comment by waylan** [comment] 2016-03-18 02:09
I just remembered #334 exists. I'm closing this as a possible duplicate. If such a feature was to be added, it would be part of that refactor.

**Closed as completed by waylan** 2016-03-18 02:09 UTC
Labels: feature, someday-maybe

**Comment by stefanv** [comment] 2016-03-18 04:56
I don't think these are the same issues.  As for motivation: I am at least the second person running into this :)  See the blog post linked to above.  The problem is that pygments _always_ returns class `highlight`, so there is no way to style your CSS to look differently for different languages.  Here is a real world example that we're running into:

We are writing blog posts that show code input and the resulting output (these are obtained by converting IPython notebooks to markdown).  The input cells are of the form:

``````
```python
def foo():
    print("123")
‏```
``````

and the output is

``````
```output
123
‏```
``````

We would like to display different color backgrounds for input and output, but that is impossible when both codeblocks are simply labeled with `highlight`.  After modifying the plugins as described in the blog post linked to, I can now add different color backgrounds.

I hope that is persuasive enough!

/cc @bnaul

**Comment by waylan** [comment] 2016-03-18 12:45
So you want a feature that Pygments doesn't even offer? That seems out of scope to me. I'll reconsider when all extensions are broken out of the main Markdown lib in version 3.0. Besides, we are in a  feature freeze while working towards version 3.0, so it wouldn't happen until then anyway.

**Comment by stefanv** [comment] 2016-03-18 17:00
No, you may be able to set the background with Pygments, but it would
require the creation of a new theme, and attaching it to the specific input
type you are interested in.  Kind of klunky.

I would consider this a bug, or at minimum an inconsistency. When the user
disables pygments in codehilite, the correct language tag is inserted. But
that tag is _replaced_ with the pygments output, instead of being inserted
inside.

I understand that you don't have confidence in my view on the matter. But
please do ask someone you trust, someone with web development experience,
for their opinion; I am confident they will agree that this is a fairly
major limitation in the code that was not well thought through.

The one other concern may be using a mixture of pygments and non-pygments
highlighting. To support that scenario, it may well be wise to change the
class tag after rendering through Pygments to something like
"pygments-<language>".

**Comment by waylan** [comment] 2016-03-18 17:33
You can change the class Pygments assigns to the output via the `css_class` [config option](https://pythonhosted.org/Markdown/extensions/code_hilite.html#usage). It just happens to be the same class for all code blocks (`codehilite`), which, IMO is the correct behavior. 

To be clear, your desired use case for the language class and the purpose of the `codehilite` class are slightly different. The `codehilite` class gives you a namespace of sorts in your CSS. Each rule regarding syntax highlighting can start with `.codehilite someclass { ... }` which avoids any potential conflicts with non-syntax highlighting classes elsewhere in your document which happen to have the same name (but are not children of `.codehilite`). However, you are asking for a way to differentiate between individual languages, which is still within the syntax highlighting (so-called) "namespace". If your requested feature was added, it would be an additional class added to the output, not a replacement of `codehilite`. Therefore, it is a feature addition, not a bug fix.

> When the user disables pygments in codehilite, the correct language tag is inserted. 

That is done so that a JavaScript based syntax highlighting library may be used. You can even force this behavior with the 'use_pygments=False' config option. Perhaps you should explore that option.

Btw, I have [thought](http://achinghead.com/syntax-highlighting-web.html)  a [lot](http://achinghead.com/marking-up-code.html) about this stuff. While those are a relatively old links, the same basic principles stand.

**Comment by mitya57** [comment] 2016-03-18 18:23
I think if it's easy to add a class with language name _alongside_ the existing `codehilite` class, then why not do that… Especially if it'll make the output with and without Pygments more similar.

**Comment by waylan** [comment] 2016-03-18 18:41
Actually, as I understand the request, including the language as a class is not _really_ the end goal. The actual request is to have a styling hook to differentiate the "input" from the "output". Of course, in some scenarios, the language of the "output" of one snippet could be the same as the language of the "input" in another snippet. Using the language class is really a hack here (which is only possible because Pygments falls back to "plain text" when an unrecognized language (like `output`) it passed in). What really should be possible is for the user to define any arbitrary class on the code block (like `input` and/or `output`) for this purpose. I expect that to be covered by #334. I'm expecting something like this to only be supported with fenced code blocks, but I'm not interesting in doing that until fenced code blocks are refactored in version 3.0.
