### ISSUE TITLE
Table of Contents generated incorrectly for headers embedded in lists (part deux)

### ISSUE THREAD

**Issue by colewerner** [Python-Markdown/markdown#407] opened 2015-04-24 13:58 UTC
Below is an example where the Table of Contents is generated incorrectly when there are headers embedded within lists:

``` markdown
# Title

[TOC]

# Section 1

## Subsection 1
Text

### Sub Subsection 1
Text

### Sub Subsection 2
1. Item 1
2. Item 2
    - Description of item 2
    #### Item 2 Subsection
    Some text

### Sub Subsection 3
TODO
```

Below is the output for the above markdown.  You can see that `Item 2 Subsection` is actually put under `Sub Subsection 3` instead of `Sub Subsection 2` in the table of contents.

![markdown_incorrect_toc](https://cloud.githubusercontent.com/assets/1071851/7320041/f813cc44-ea67-11e4-9766-dec82fa66195.png)

**Comment by facelessuser** [comment] 2015-04-24 23:19
I'm not seeing this on 2.6.2.

Are you sure another extensions isn't introducing issues?

```
import markdown


src = '''# Title

[TOC]

# Section 1

## Subsection 1
Text

### Sub Subsection 1
Text

### Sub Subsection 2
1. Item 1
2. Item 2
    - Description of item 2
    #### Item 2 Subsection
    Some text

### Sub Subsection 3
TODO
'''

print(markdown.markdown(src, extensions=['markdown.extensions.toc']))
```

![screenshot - 4_24_2015 5_17_29 pm](https://cloud.githubusercontent.com/assets/1055125/7330104/d6b80536-eaa5-11e4-9798-40c5ac48d5a6.png)

**Comment by waylan** [comment] 2015-04-27 02:34
I can't reproduce this either. Closing this as no problem exists in the current codebase.

**Closed as completed by waylan** 2015-04-27 02:34 UTC

**Comment by colewerner** [comment] 2015-04-27 12:01
It must be something on my end.  I was running it against 2.6.1.  I did upgrade to 2.6.2 and saw the same thing.  I'm using sublime with Markdown Editing and Markdown Preview extensions installed.  If I figure it out I'll post back here.

**Comment by froschdesign** [comment] 2017-12-28 13:14
@facelessuser
Sorry, but in your screenshot the headline "Item 2 Subsection" is included!

@facelessuser @waylan 
The problem still exists in version 2.6.10.

```html
<div class="toc">
    <ul>
        <li><a href="#title">Title</a></li>
        <li><a href="#section-1">Section 1</a>
            <ul>
                <li><a href="#subsection-1">Subsection 1</a>
                    <ul>
                        <li><a href="#sub-subsection-1">Sub Subsection 1</a>
                        </li>
                        <li><a href="#sub-subsection-2">Sub Subsection 2</a>
                            <ul>
                                <li><a href="#item-2-subsection">Item 2 Subsection</a></li>
                            </ul>
                        </li>
                        <li><a href="#sub-subsection-3">Sub Subsection 3</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>
    </ul>
</div>
```

The same for headlines in blockqoutes:

```html
```

**Comment by facelessuser** [comment] 2017-12-28 15:13
@colewerner, with the latest release (`2.6.10`), I am still getting proper output:

```
<div class="toc">
<ul>
<li><a href="#title">Title</a></li>
<li><a href="#section-1">Section 1</a><ul>
<li><a href="#subsection-1">Subsection 1</a><ul>
<li><a href="#sub-subsection-1">Sub Subsection 1</a></li>
<li><a href="#sub-subsection-2">Sub Subsection 2</a><ul>
<li><a href="#item-2-subsection">Item 2 Subsection</a></li>
</ul>
</li>
<li><a href="#sub-subsection-3">Sub Subsection 3</a></li>
</ul>
</li>
</ul>
</li>
</ul>
</div>
```

<div class="toc">
<ul>
<li><a href="#title">Title</a></li>
<li><a href="#section-1">Section 1</a><ul>
<li><a href="#subsection-1">Subsection 1</a><ul>
<li><a href="#sub-subsection-1">Sub Subsection 1</a></li>
<li><a href="#sub-subsection-2">Sub Subsection 2</a><ul>
<li><a href="#item-2-subsection">Item 2 Subsection</a></li>
</ul>
</li>
<li><a href="#sub-subsection-3">Sub Subsection 3</a></li>
</ul>
</li>
</ul>
</li>
</ul>
</div>

**Comment by waylan** [comment] 2017-12-28 15:42
@facelessuser, note that @colewerner's last comment was made 2.5+ years ago. I'm not sure why this discussion suddenly showed up as being updated. Perhaps someone left a new comment, which they then deleted before we had a chance to see it.

**Comment by facelessuser** [comment] 2017-12-28 15:54
Thanks. I got an email with a different message. They must have emailed me directly, or posted and removed the post.

Anyways, disregard my last post.
