### ISSUE TITLE
nested bullet points to nested list is not being converted 

### ISSUE THREAD

**Issue by Poornahandra** [Python-Markdown/markdown#1159] opened 2021-07-24 17:44 UTC
if markdown has nested list as below then html do not have nested list
* abcd
    * pqr
    * lmno
* xyz

**Comment by facelessuser** [comment] 2021-07-25 01:30
What HTML does this give you? I get this which looks correct and has nested lists:

```html
<ul>
<li>abcd<ul>
<li>pqr</li>
<li>lmno</li>
</ul>
</li>
<li>xyz</li>
</ul>
```

**Comment by Poornahandra** [comment] 2021-07-25 07:22
I am getting this as processed content
<ul>
<li>abcd<ul>
<li>pqr</li>
<li>lmno</li>
<li>xyz</li>
</ul>

**Comment by facelessuser** [comment] 2021-07-25 14:14
Can you post actual input markdown and actual output HTML so we can attempt we can verify and try to recreate?

**Comment by facelessuser** [comment] 2021-07-25 14:42
I've verified that I cannot reproduce your issue on the latest Python Markdown.

```py
import markdown

md = """
* abcd
    * pqr
    * lmno
* xyz
"""

print('=== Markdown Version ===')
print(markdown.__version__)

print('=== Input ===')
print(md)

html = markdown.markdown(md)
print('=== Output ===')
print(html)
```

The output clearly shows the input used and the output with nested `ul` elements.

```
=== Markdown Version ===
3.3.4
=== Input ===

* abcd
    * pqr
    * lmno
* xyz

=== Output ===
<ul>
<li>abcd<ul>
<li>pqr</li>
<li>lmno</li>
</ul>
</li>
<li>xyz</li>
</ul>
```

I would consider this most likely a user error unless an actual, correct example is shown to not work.

**Comment by Poornahandra** [comment] 2021-07-25 15:23
Hi, may be I got the issue.
I have this markdown content (nested lists separated by 2 spaces) and its output in the right.
![image](https://user-images.githubusercontent.com/38465746/126904222-6f057a33-e3a3-4e94-99dc-7a3ec4d67862.png)
and converted output of it looks like 
![image](https://user-images.githubusercontent.com/38465746/126904331-7c11f618-d94b-4712-93cd-c2652735decc.png)
So 2 space separation is not considering as nested whereas markdown does.
Thank you

**Comment by facelessuser** [comment] 2021-07-25 15:25
The documentation notes that 4 spaces must be used. Some parsers may approach this differently, but Python Markdown has always required this.

**Comment by Poornahandra** [comment] 2021-07-25 15:28
Okay, thank you for the quick response. May be I can have restrictions/guidelines set for the documentation. And above all, this implementation is very helpful and eased my task significantly. 
I appreciate the effort put to develop this.

**Comment by waylan** [comment] 2021-07-27 14:16
I'm closing this as user error. However, in the future, please provide code in code blocks, not screenshots of your code, which are not helpful.

**Closed as completed by waylan** 2021-07-27 14:16 UTC
Labels: support
