### ISSUE TITLE
codehilite linenums not fully aligned to pygments' linenos

### ISSUE THREAD

**Issue by fernandezcuesta** [Python-Markdown/markdown#394] opened 2015-03-09 09:56 UTC
As coded in [line 117](https://github.com/waylan/Python-Markdown/blob/master/markdown/extensions/codehilite.py#L117) `linenums` is transparently passed to pygments' `linenos`.
According to [pygments documentation](http://pygments.org/docs/formatters/):

> linenos
>     If set to 'table', output line numbers as a table with two cells, one containing the line numbers, the other the whole code. This is copy-and-paste-friendly, but may cause alignment problems with some browsers or fonts. If set to 'inline', the line numbers will be integrated in the `pre` tag that contains the code (that setting is new in Pygments 0.8).
>     For compatibility with Pygments 0.7 and earlier, every true value except 'inline' means the same as 'table' (in particular, that means also True).
>     The default value is False, which means no line numbers at all.

What I see is that linenums is boolean, thus forcing codehilite to use either `linenos=table` when True or `linenos=False` otherwise.

Would be nice to allow using `linenos=inline` too.

**Comment by waylan** [comment] 2015-03-09 18:27
@fernandezcuesta thank you for your suggestion. I find it interesting that this feature was added in Pygments version 0.8 and today Pygments is at version 2.0.2. And yet, this is the first time I have received a request for support of the "inline" feature.

The fact is, I am not particularly fond of their inline formatting as it is quite frustrating when you want to copy and paste some code. Each line has the line number at the beginning which then needs to be deleted line-by-line. That said, I agree that the "table" format is not perfect either.

I'm marking this as a duplicate of #334. While that issue addresses a different Pygments option, I'm looking at re-factoring support for all Pygments options so all the work should fall under that issue.

**Closed as completed by waylan** 2015-03-09 18:27 UTC
