### ISSUE TITLE
Empty span tags in codehilite divs

### ISSUE THREAD

**Issue by arkanovicz** [Python-Markdown/markdown#558] opened 2017-04-08 15:19 UTC
Hi.
There seems to be a regression in version 2.6.7, where empty <span></span> tags are added at the beginning of every <div class="codehilite"><pre> section.
This wasn't the case in 2.6.6.

**Comment by facelessuser** [comment] 2017-04-08 15:24
You should provide some Markdown source and HTML output so we can better understand your issue. I'm not sure what you are describing, but with the source and output HTML, I can probably tell what's going on.  Also, it would be good to mention what other extensions you are using.

**Comment by arkanovicz** [comment] 2017-04-08 15:54
Simple example:

Let test.md contain:

<pre>
there:

    this may be code

done
</pre>

When running:

    $ markdown_py -xcodehilite test.md

the result is:

    <p>there:</p>
    <div class="codehilite"><pre><span></span>this may be code
    </pre></div>
    <p>done</p>

**Comment by facelessuser** [comment] 2017-04-08 16:26
Are you complaining about the span at the beginning of the code block? If so, that is by design and introduced by Pygments in recent versions. I don't have the link to the specific issue in Pygments off hand that spawned this change, but it was a change by design.

**Comment by arkanovicz** [comment] 2017-04-08 17:05
So it's not a bug, it's a feature... I don't see the benefit, and it looks more like a side effect, but I won't argue any further, it's a minor issue. The only reason I pointed it out was that it induces noise in site changelogs...

**Comment by facelessuser** [comment] 2017-04-08 17:18
It isn't introduced by Python Markdown.  Check out the Pygments repo on Bitbucket to find out more.  It was solving a very specific issue which I don't recall if the top of my head.

**Comment by facelessuser** [comment] 2017-04-08 19:32
Found the Pygments issue: https://bitbucket.org/birkenfeld/pygments-main/issues/1111/an-empty-line-at-first-has-been-ignored.

**Comment by arkanovicz** [comment] 2017-04-08 20:17
Wow. So it's a hack :-) Thanks for satisfying my curiosity.

**Comment by waylan** [comment] 2017-04-09 21:44
@facelessuser thanks for tracking this down. As this is an upstream issue (outside our control), I'm closing this. 

As an aside, I've been aware of Pygments sometimes misaligning line numbers for years, but given the inconsistency, I was never able to figure out what caused it. Interesting to finally get that answered. Although I agree, the fix feels like a hack. That said, I never liked the way they do line numbers anyway.

**Closed as completed by waylan** 2017-04-09 21:44 UTC
