### ISSUE TITLE
the > is unexpected escaped twice.

### ISSUE THREAD

**Issue by a358003542** [Python-Markdown/markdown#802] opened 2019-03-07 06:15 UTC
here is the testing code:
```

from markdown import Markdown

settings =  {'extension_configs': {'markdown.extensions.codehilite': {'css_class': 'highlight'}, 'markdown.extensions.toc': {}, 'markdown.extensions.fenced_code': {}, 'markdown.extensions.extra': {}, 'markdown.extensions.meta': {}}, 'output_format': 'html5', 'extensions': ['markdown.extensions.codehilite', 'markdown.extensions.toc', 'markdown.extensions.fenced_code', 'markdown.extensions.extra', 'markdown.extensions.meta']}
md = Markdown(**settings)


string = """在改变某个ndarray对象的dtype的时候，原ndarray对象实际上被删除了，等于重新创建了一个ndarray对象。可以通过上面的类型声明来直接进行转换，如:

    >>> t = np.array([1,2,3],dtype='int8')
    >>> t.dtype
    dtype('int8')
    >>> new_t = np.int32(t)
    >>> new_t.dtype
    dtype('int32')

"""

res = md.convert(string)


print(res)
```

The output is:

```
<p>在改变某个ndarray对象的dtype的时候，原ndarray对象实际上被删除了，等于重新创建了一个ndarray对象。可以通过上面的类型声明来直接进行转换，如:</p>
<div class="highlight"><pre><span></span>&amp;gt;&amp;gt;&amp;gt; t = np.array([1,2,3],dtype=&#39;int8&#39;)
&amp;gt;&amp;gt;&amp;gt; t.dtype
dtype(&#39;int8&#39;)
&amp;gt;&amp;gt;&amp;gt; new_t = np.int32(t)
&amp;gt;&amp;gt;&amp;gt; new_t.dtype
dtype(&#39;int32&#39;)
</pre></div>
```

It seems the `>` symbol has escaped to `&gt;` and escaped again to `&amp;gt;` . 

If the code is surrounded by the ```

 symbol . then everything is fine.

**Comment by mitya57** [comment] 2019-03-07 09:53
This is a duplicate of #725. It will be fixed in the next release (3.1).

**Closed as completed by mitya57** 2019-03-07 09:53 UTC
Labels: duplicate
