### ISSUE TITLE
Wrong html output when parsing UnorderedList and OrderedList?

### ISSUE THREAD

**Issue by Ricky-Hao** [Python-Markdown/markdown#612] opened 2017-12-18 08:04 UTC
#### Source markdown
```markdown
* ul_1
* ul_2
1. ol_1
2. ol_2
```
#### Output HTML
```html
<ul>
<li>ul_1</li>
<li>ul_2</li>
<li>ol_1</li>
<li>ol_2</li>
</ul>
```
#### Except
```html
<ul>
<li>ul_1</li>
<li>ul_2</li>
</ul>
<ol>
<li>ol_1</li>
<li>ol_2</li>
</ol>
```
#### Problem
It seens the parser parse the UL and OL together?

And if OL write before UL, it would output `<ol>` for all item.

**Comment by facelessuser** [comment] 2017-12-18 14:43
This is expected behavior.

1. You should be separating your different lists with a new line, but Markdown will still render it as one list.

2. To get the list transition to work as expected, Python Markdown ships with [Sane Lists](https://python-markdown.github.io/extensions/sane_lists/).

**Comment by waylan** [comment] 2017-12-18 16:35
A quick search shows that this is a duplicate of #422 #175, #107 and #64. #64 provides a full explanation of the current behavior. and #422 points to the [documentation][1] (which also provides a workaround):

> * Consecutive Lists
> 
>     While the syntax rules are not clear on this, many implementations (including the original) do not end one list and start a second list when the list marker (asterisks, pluses, hyphens, and numbers) changes. For consistency, Python-Markdown maintains the same behavior with no plans to change in the foreseeable future. That said, the [Sane List Extension][2] is available to provide a less surprising behavior.

[1]: https://python-markdown.github.io/#differences
[2]: https://python-markdown.github.io/extensions/sane_lists/

**Closed as completed by waylan** 2017-12-18 16:35 UTC
