### ISSUE TITLE
attr_list for table and ul/ol ?

### ISSUE THREAD

**Issue by ikus060** [Python-Markdown/markdown#668] opened 2018-06-17 12:50 UTC
I see multiple issues (#312, #227, #505, #594, #600) related to `attr_list` applied to table, ol or ul and I can't figure out if we settle on a specific syntax. Looking at the code it's not obvious if it's possible to assign class to ol/ul.

If not supported, I'm wondering why. Clearly, it's a highly requested feature and I see multiple proposal for syntax and implementation.

If supported, what is the right syntax ? and may we get this documented on the web site.

Thanks !

**Comment by waylan** [comment] 2018-06-18 11:31
I don't know what is so confusing. Sure, various non-members have proposed various solutions on the cited issues. However, my position has remained constant. Regarding [lists][1] I explain that:

> ...the markdown syntax has no concept of a ul or ol. They are simply implied by the fact that we have list items.

And [tables][2]:

> ...how would one differentiate between attributes defined on a row, or on a table. The syntax only defines the cells, the rows and table are inferred.

It is not possible to assign attributes to elements which don't actually exist in the document. Therefore, we will never attempt to support such a feature, regardless of how many requests or proposals we receive. Of course, anyone is free to create their own extensions which have any behavior they want.

This is being closed as another duplicate of #227 and #312.

[1]: https://github.com/Python-Markdown/markdown/issues/227#issuecomment-20223738
[2]: https://github.com/Python-Markdown/markdown/issues/312#issuecomment-44227093

**Closed as completed by waylan** 2018-06-18 11:31 UTC
