### ISSUE TITLE
Incorrect Output

### ISSUE THREAD

**Issue by gopar** [Python-Markdown/markdown#565] opened 2017-05-16 20:12 UTC
```python
import markdown
body = """
hey here is some test
`` `
#ifdef
    Code
#endif
`` `
More text
"""
print(markdown.markdown(body))
```

Produces the following:

```html
<p>hey here is some test</p>
<p>```</p>
<h1>ifdef</h1>
<pre><code>Code
</code></pre>
<h1>endif</h1>
<p>```</p>
<p>More text</p>
```

*Note:* I  put the a space in between the backticks in the code so it won't be cut off (Markdown gets confused

**Comment by waylan** [comment] 2017-05-16 20:32
I can only speculate on what you expected here, but as far as I can tell, this is correct. A few notes:

* Fenced code blocks are not part of standard Markdown. They are a non-standard addon. If you would like Python-Markdown to parse them (it's not clear if that was your goal here), then you can use the [Fenced Code Blocks][1] extension.

* The opening and closing deliminators for a fenced code block require three backticks with no spaces. You indicate that you inserted the spaces intentionally. It's not clear to me if you meant that applies to the input to Python-Markdown or to your post here on GitHub. If you meant in your input to Python-Markdown, then you should remove the spaces. If you meant here on GitHub, then you could indent the entire sample Markdown document to put it in a code block.

* If for some reason you do not want a fenced code block, then each line of your code should be indented by at least four spaces to put it in a code block. This will ensure your formatting is preserved.

[1]: https://pythonhosted.org/Markdown/extensions/fenced_code_blocks.html

**Comment by waylan** [comment] 2017-11-28 19:53
I also missed that your fenced code block needs to be surrounded by blank lines. In other words, you need a blank line before your opening deliminator and a blank line after your closing deliminator.

As this appears to be user error and not a bug, I'm closing this.

**Closed as completed by waylan** 2017-11-28 19:53 UTC
