### ISSUE TITLE
wrong list markup

### ISSUE THREAD

**Issue by sphaero** [Python-Markdown/markdown#450] opened 2015-12-22 18:25 UTC
Just a simple

```
* 1
* 2
* 3

* 4
* 5
* 6
```

ends up as: (notice the p tags)

```
<ul>\n
<li>1</li>\n
<li>2</li>\n
<li>\n
<p>3</p>\n
</li>\n
<li>\n
<p>4</p>\n
</li>\n
<li>5</li>\'
<li>6</li>\n
</ul>
```

I guess this is wrong?

code example:

```
>>> pprint.pprint(markdown.markdown("* 1\n* 2\n* 3\n\n* 4\n* 5\n* 6\n"))
```

**Comment by waylan** [comment] 2015-12-22 20:18
This is intended behavior. Go read the [Syntax rules](http://daringfireball.net/projects/markdown/syntax#list), particularly the part about multiple paragraphs in a list item. The blank line is what triggers the paragraph mode. In fact, all implementations do [something](http://johnmacfarlane.net/babelmark2/?normalize=1&text=*+1%0A*+2%0A*+3%0A%0A*+4%0A*+5%0A*+6) like this. Note that Python-Markdown follows the reference implementation.

As there is no bug here, I am closing this.

**Closed as completed by waylan** 2015-12-22 20:18 UTC
